'use client';
import {useEffect,useState} from 'react';
import {Clock} from 'lucide-react';
import {elapsedLabel,revisitLabel,revisitDue,scheduleVisit,type ActivityTiming} from '@/lib/activity-time';
export function useClassClock(){const [now,setNow]=useState(0);useEffect(()=>{const tick=()=>setNow(Date.now());tick();const id=setInterval(tick,10000);document.addEventListener('visibilitychange',tick);return()=>{clearInterval(id);document.removeEventListener('visibilitychange',tick);};},[]);return now;}
export function ActivityClock({timing}:{timing?:ActivityTiming}){const now=useClassClock();return <span className="activity-clock"><span>{now?elapsedLabel(timing,now):'시간 확인 중'}</span>{now>0&&revisitLabel(timing,now)&&<span className={'activity-revisit '+(revisitDue(timing,now)?'due':'')}><Clock size={15}/>{revisitLabel(timing,now)}</span>}</span>;}
export function ActivityTimingControls({timing,change,disabled,undoKey='',onTap}:{timing?:ActivityTiming;change:(t:ActivityTiming)=>void;disabled:boolean;undoKey?:string;onTap?:(key:string,t:ActivityTiming)=>void}){
 const [minutes,setMinutes]=useState('5'),[custom,setCustom]=useState('7');const delay=minutes==='none'?null:Number(minutes==='custom'?custom:minutes),invalid=delay!==null&&(!Number.isInteger(delay)||delay<1||delay>1440),blocked=disabled||invalid;
 return <details className="activity-timing-controls"><summary>다시 볼 시점{timing?.visitedAt?' · 방문 표시 있음':''}</summary><label>지금부터<select aria-label="다시 볼 시점" value={minutes} onChange={e=>setMinutes(e.target.value)} disabled={disabled}>{[3,5,10,15,20,30].map(n=><option key={n} value={n}>{n}분 뒤</option>)}<option value="custom">직접 입력</option><option value="none">지정하지 않음</option></select></label>{minutes==='custom'&&<label>몇 분 뒤<input type="number" inputMode="numeric" min="1" max="1440" step="1" aria-label="다시 볼 시간 직접 입력 (분)" value={custom} onChange={e=>setCustom(e.target.value)} disabled={disabled}/></label>}<div className="task-actions"><button aria-pressed={undoKey==='set'} disabled={undoKey==='set'?false:blocked} onClick={()=>onTap?onTap('set',scheduleVisit(timing,invalid?null:delay,false)):change(scheduleVisit(timing,delay,false))}>{undoKey==='set'?'시점 지정 취소':'시점만 지정'}</button><button aria-pressed={undoKey==='visit'} disabled={undoKey==='visit'?false:blocked} onClick={()=>onTap?onTap('visit',scheduleVisit(timing,invalid?null:delay,true)):change(scheduleVisit(timing,delay,true))}>{undoKey==='visit'?'방문·재방문 지정 취소':'다녀옴 · '+(minutes==='none'?'신호 해제':(invalid?'시간 입력':delay+'분 뒤 다시'))}</button></div><p className="hint">배정 후 경과시간은 유지합니다. 방문 표시는 활동 완료와 별도입니다.</p></details>;
}
