'use client';
import {useEffect,useLayoutEffect,useRef,useState} from 'react';
import {Check,ArrowRight,Plus,ChevronUp,ChevronDown,Copy,ClipboardCheck} from 'lucide-react';
import {Checkbox} from '@/components/ui/checkbox';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/ui/select';
import {Dialog,DialogContent,DialogDescription,DialogHeader,DialogTitle} from '@/components/ui/dialog';
import {activityChoices,blankCloseout,blankReport,classPart,completeCloseout,entity,isOpen,isTest,reportCheckKey,reportConfirmationKey,reviewBasis,task,taskLabels,values,type ClassEvent,type Closeout,type Report,type Task} from '@/lib/classroom';
import {ActivityClock,ActivityTimingControls} from './activity-clock';
import {CloseoutCandidates} from './conversation-candidates';
import {closeoutCurrent,closeoutEvidenceBasis} from '@/lib/closeout-review';
import {classroomView} from '@/lib/classroom-view';
import {RecordProgress} from './record-progress';
import {SwipeDeleteCard} from './swipe-delete-card';
import {assignedTiming,transitionTiming} from '@/lib/activity-time';
import {cardRevisions} from '@/lib/observation-cards';
import {tapPatch,matchesTap,type TapUndo} from '@/lib/tap-undo';
import {latest,parse,students,type Entry,type Session,type Student} from '@/lib/notebook';
import {trackerHandoff} from '@/lib/handoff';
import type {NotebookData} from '@/lib/projection';
import type {RevisionMode} from '@/lib/outbox';
import {CurriculumAssignment,type AssignmentDraft} from './curriculum-picker';
import {scopeText,type CurriculumCatalog} from '@/lib/curriculum';
import {blankDiary,diaryLimit,diaryReady,parentInputFromClass,previewParentDiary,type PublicDiary} from '@/lib/diary-draft';
import {AcademyPanel} from './academy-panel';
import {HomeworkPanel} from './homework-picker';
import {applyActivityScope,mergeActivityScopeDraft,type ActivityScopeDraft} from '@/lib/activity-scope';
import {ActivityScopeEditor} from './activity-scope-editor';
import {havrutaState,havrutaLabel,havrutaStatePatch} from '@/lib/havruta';

type Save=(kind:string,entityId:string,data:unknown,originDate?:string,baseId?:string,mode?:RevisionMode)=>Promise<void>;
function useForm<T extends object>(initial:T,save:(v:T,baseId:string,mode:RevisionMode)=>Promise<void>,fail:(e:unknown)=>void,version=''){
 const [value,setValue]=useState(initial),ref=useRef(initial),touched=useRef(false),base=useRef(version),undo=useRef<TapUndo<T>|null>(null);
 useEffect(()=>{if(JSON.stringify(initial)===JSON.stringify(ref.current)){base.current=version;touched.current=false;}else if(!touched.current){ref.current=initial;setValue(initial);base.current=version;undo.current=null;}},[JSON.stringify(initial),version]);
 function write(p:Partial<T>,mode:RevisionMode){const next={...ref.current,...p};ref.current=next;touched.current=true;setValue(next);void save(next,base.current,mode).catch(fail);}
 function change(p:Partial<T>,mode:RevisionMode='draft'){undo.current=null;write(p,mode);}
 function toggle(key:string,p:Partial<T>){const result=tapPatch(ref.current,undo.current,key,p);undo.current=result.undo;write(result.patch,'event');}
 async function commit(p:Partial<T>){const before=ref.current,wasTouched=touched.current,next={...before,...p};undo.current=null;ref.current=next;touched.current=true;setValue(next);try{await save(next,base.current,'event');}catch(e){if(ref.current===next){ref.current=before;touched.current=wasTouched;setValue(before);}throw e;}}
 return [value,change,toggle,(key:string)=>matchesTap(ref.current,undo.current,key),commit] as const;
}
export function Pick({value,onChange,items,label}:{value:string;onChange:(s:string)=>void;items:[string,string][];label:string}){return <Select value={value||'none'} onValueChange={s=>onChange(s==='none'?'':s)}><SelectTrigger aria-label={label}><SelectValue/></SelectTrigger><SelectContent>{items.map(([id,name])=><SelectItem value={id||'none'} key={id||'none'}>{name}</SelectItem>)}</SelectContent></Select>;}
export function Tick({checked,onChange,children}:{checked:boolean;onChange:(v:boolean)=>void;children:React.ReactNode}){return <label className="checkbox-label"><Checkbox checked={checked} onCheckedChange={v=>onChange(v===true)}/><span>{children}</span></label>;}
export function formatTime(v:string){return v?new Date(v).toLocaleTimeString('ko-KR',{timeZone:'Asia/Seoul',hour:'2-digit',minute:'2-digit'}):'';}
function Field({label,value,onChange,placeholder,max=12000}:{label:string;value:string;onChange:(s:string)=>void;placeholder?:string;max?:number}){return <label className="field"><span>{label}</span><textarea value={value} onChange={e=>onChange(e.target.value)} placeholder={placeholder} maxLength={max}/></label>;}
export function Observation({session,events,save,fail}:{session:Session;events:Entry[];save:(v:unknown,baseId:string)=>Promise<void>;fail:(e:unknown)=>void}){const initial={observed:'',studentSaid:'',next:'',...parse(latest(events,'observation'))};const [v,change]=useForm<{observed:string;studentSaid:string;next:string}>(initial,save,fail,latest(events,'observation')?.id||'');return <section className="panel"><h3>직후 관찰</h3><div className="field-grid"><Field label="강사가 직접 본 모습" value={v.observed} onChange={observed=>change({observed})} placeholder="직접 확인한 모습·힌트 뒤 변화"/><Field label="학생이 말한 내용" value={v.studentSaid} onChange={studentSaid=>change({studentSaid})} placeholder="학생의 자기보고"/><Field label="다시 확인할 일·다음 약속" value={v.next} onChange={next=>change({next})} placeholder="다음에 무엇을 확인할지"/></div><p className="hint">{session.title}에 연결됩니다. 입력은 이 기기에 먼저 보관합니다.</p>{events.filter(e=>e.kind==='observation').length>1&&<details><summary>이전 관찰 수정 이력</summary>{events.filter(e=>e.kind==='observation').slice(0,-1).map(e=><div className="history" key={e.id}><b>{formatTime(e.created_at)} · 이전 내용</b><p>{parse(e).observed}</p><p>학생 발언 · {parse(e).studentSaid||'없음'}</p><p>다음 확인 · {parse(e).next||'없음'}</p></div>)}</details>}</section>;}

export function Activities({studentId,date,ledger,save,fail,compact=false,catalog}:{studentId:string;date:string;ledger:ClassEvent[];save:Save;fail:(e:unknown)=>void;compact?:boolean;catalog?:CurriculumCatalog|null}){
 const events=ledger.filter(e=>e.student_id===studentId&&e.kind==='activity'),today=events.filter(e=>JSON.parse(e.body).workDate===date),pending=events.filter(e=>JSON.parse(e.body).workDate<date&&(isOpen(JSON.parse(e.body))||JSON.parse(e.body).cancelled));
 const plan=ledger.find(e=>e.entity_id===entity('plan',studentId,date));const titles=activityChoices(plan?JSON.parse(plan.body).titles:undefined);const [edit,setEdit]=useState(false),[custom,setCustom]=useState(''),[assignOpen,setAssignOpen]=useState(()=>!today.some(e=>!JSON.parse(e.body).cancelled));
 function reorder(i:number,delta:number){const next=[...titles];[next[i],next[i+delta]]=[next[i+delta],next[i]];void save('plan',entity('plan',studentId,date),{...values(plan,{titles}),titles:next}).catch(fail);}
 const [recent,setRecent]=useState<Record<string,{id:string;body:Task}>>({}),recentRef=useRef(recent),assigning=useRef(false),ledgerRef=useRef(ledger);
 const [scopeActivity,setScopeActivity]=useState(''),scopeEvent=events.find(e=>e.entity_id===scopeActivity);
 async function retainScope(activityId:string,draft:ActivityScopeDraft|null){const id=entity('plan',studentId,date),row=ledgerRef.current.find(e=>e.entity_id===id);await save('plan',id,mergeActivityScopeDraft(values(row,{titles}),activityId,draft),date,row?.id||'','draft');}
 // Notebook and QuickWork both key this component by student/day.
 useLayoutEffect(()=>{ledgerRef.current=ledger;},[ledger]);
 function reversible(title:string){const prior=recent[title];if(!prior)return false;const current=ledger.find(e=>e.entity_id===prior.id);return !current||JSON.stringify({...task('',date),...JSON.parse(current.body)})===JSON.stringify(prior.body);}
 async function assign(title:string){
  if(assigning.current)return;assigning.current=true;
  try{const prior=recentRef.current[title],current=prior&&ledgerRef.current.find(e=>e.entity_id===prior.id),unchanged=prior&&(!current||JSON.stringify({...task('',date),...JSON.parse(current.body)})===JSON.stringify(prior.body));
   const id=unchanged?prior.id:crypto.randomUUID(),body:Task=unchanged?{...prior.body,cancelled:!prior.body.cancelled}:{...task(title,date),timing:assignedTiming()};
   await save('activity',id,body,date,unchanged?(current?.id||''):'','event');const next={...recentRef.current,[title]:{id,body}};recentRef.current=next;setRecent(next);
  }catch(e){throw e;}finally{assigning.current=false;}
 }
 return <div className={compact?'activities compact-activities':'activities'}>
 <Dialog open={!!scopeEvent} onOpenChange={v=>{if(!v)setScopeActivity('');}}><DialogContent className="a-action-sheet translate-x-0 translate-y-0 sm:translate-x-[-50%] sm:translate-y-[-50%]"><DialogHeader><DialogTitle>배정 범위 수정</DialogTitle><DialogDescription>기존 활동에 교재·단원·쪽수 연결 · 새 활동이나 완료를 만들지 않습니다.</DialogDescription></DialogHeader>{scopeEvent&&<ActivityScopeEditor key={scopeEvent.entity_id} event={scopeEvent} studentId={studentId} date={date} catalog={catalog} draft={values(plan,{activityScopeDrafts:[] as ActivityScopeDraft[]}).activityScopeDrafts.find(d=>d.activityId===scopeEvent.entity_id)} retain={d=>retainScope(scopeEvent.entity_id,d)} onApply={async(d,c)=>{const current=ledgerRef.current.find(e=>e.entity_id===d.activityId),next=applyActivityScope(current,d,studentId,date,c);await save('activity',d.activityId,next,current!.class_date,current!.id,'event');}} onDone={()=>setScopeActivity('')} fail={fail}/>}</DialogContent></Dialog>
 <CurriculumAssignment studentId={studentId} date={date} initialCatalog={catalog} draft={values(plan,{scopeDraft:undefined as AssignmentDraft|undefined}).scopeDraft} retain={draft=>save('plan',entity('plan',studentId,date),{...values(plan,{titles}),scopeDraft:draft},date,undefined,'draft')} assign={async(title,scope,id)=>{await save('activity',id,{...task(title,date),scope,range:scopeText(scope),timing:assignedTiming()},date,'','event');}} fail={fail}/><section className="panel assign-panel"><div className="section-title"><button className="field-assign-toggle" aria-expanded={assignOpen} onClick={()=>setAssignOpen(!assignOpen)}><Plus size={18}/><span>활동 배정</span><ChevronDown size={16}/></button>{assignOpen&&<button className="quiet" onClick={()=>setEdit(!edit)}>{edit?'편집 마침':'순서 편집'}</button>}</div><div className="assignment-choices" hidden={!assignOpen}><div className="activity-buttons">{titles.map((title,i)=><div className="activity-option" key={i}>{edit?<><span>{i+1}. {title}</span><button aria-label={title+' 위로'} disabled={!i} onClick={()=>reorder(i,-1)}><ChevronUp size={16}/></button><button aria-label={title+' 아래로'} disabled={i===titles.length-1} onClick={()=>reorder(i,1)}><ChevronDown size={16}/></button></>:<button aria-pressed={!!recent[title]&&reversible(title)&&!recent[title].body.cancelled} onClick={()=>void assign(title).catch(fail)}><Plus size={16}/>{title}{reversible(title)?recent[title].body.cancelled?' · 배정 복원':' · 배정 취소':''}</button>}</div>)}</div><details className="custom-activity"><summary>직접 활동 입력</summary><div className="inline-form"><input aria-label="직접 배정할 활동" value={custom} onChange={e=>setCustom(e.target.value)} placeholder="직접 활동 입력" maxLength={150}/><button aria-pressed={!!custom.trim()&&reversible(custom.trim())&&!recent[custom.trim()].body.cancelled} disabled={!custom.trim()} onClick={()=>{void assign(custom.trim()).catch(fail);}}>{reversible(custom.trim())?recent[custom.trim()].body.cancelled?'배정 복원':'배정 취소':'배정'}</button>{edit&&<button disabled={!custom.trim()} onClick={()=>void save('plan',entity('plan',studentId,date),{...values(plan,{titles}),titles:[...titles,custom.trim()]}).then(()=>setCustom('')).catch(fail)}>후보에 추가</button>}</div></details></div></section>
 <div className="activity-lanes">{(['student','teacher'] as const).map(lane=><section className="lane" key={lane}><h3>{lane==='student'?'학생 활동':'강사 진행·확인'} <span>{today.filter(e=>JSON.parse(e.body).lane===lane&&isOpen(JSON.parse(e.body))).length}</span></h3>{today.filter(e=>JSON.parse(e.body).lane===lane).map(e=><TaskCard key={e.entity_id} event={e} all={events} save={save} fail={fail} onScope={()=>setScopeActivity(e.entity_id)}/>)}{!today.some(e=>JSON.parse(e.body).lane===lane)&&<p className="empty-small">배정 전</p>}</section>)}</div>
 <details className="panel previous-work"><summary>이전 수업에서 남은 일 <span>{pending.filter(e=>isOpen(JSON.parse(e.body))).length}</span></summary><p className="hint">보강·숙제로 자동 이동하지 않습니다. 이번 만남에 이어 할 일을 직접 선택하세요.</p>{pending.map(e=><PendingTaskCard key={e.entity_id} event={e} date={date} save={save} fail={fail}/>)}{!pending.length&&<p className="empty-small">기록된 이전 미해결 일이 없습니다.</p>}</details></div>;
}
export function TaskCard({event,all,save,fail,onScope}:{event:ClassEvent;all:ClassEvent[];save:Save;fail:(e:unknown)=>void;onScope?:()=>void}){
 const [t,put,toggle,canUndo,commit]=useForm(values(event,task('',event.class_date)),(v,b,mode)=>save('activity',event.entity_id,v,event.class_date,b,mode),fail,event.id);const [history,setHistory]=useState<ClassEvent[]|null>(null);
 const change=(p:Partial<Task>,mode:RevisionMode='draft')=>put({...p,...(p.state?{timing:transitionTiming(t.timing,p.state)}:{})},mode);
 const control=(p:Partial<Task>)=>change(p,'event');
 function stateTap(state:Task['state']){if(t.havruta&&t.cancelled)return;const next=havrutaState(t)===state?'assigned':state;toggle('state:'+state,havrutaStatePatch(t,next));}
 const pre=all.find(e=>e.entity_id===t.prerequisite),blocked=t.relation==='required'&&(!pre||JSON.parse(pre.body).cancelled||havrutaState(JSON.parse(pre.body))!=='done')&&!t.overrideReason;
 return <SwipeDeleteCard label={t.title} revision={event.id+JSON.stringify(t)} className={'task-card task-'+havrutaState(t)} deleted={!!t.cancelled} onDelete={()=>commit({cancelled:true})} onRestore={()=>commit({cancelled:false})} onError={fail} heading={<span className="task-title"><strong>{t.title}</strong><span className={'status-tag '+(t.state==='check'?'attention':'')}>{t.havruta?havrutaLabel(t):taskLabels[t.state]}</span></span>}>{t.title==='개념백지테스트'&&<p className="hint">강사 질문 · 학생 작성·설명</p>}<ActivityClock timing={t.timing}/>{t.havruta&&<p className="hint">공동 풀이 · 개인 발언·숙달은 자동 판정하지 않습니다.{t.havruta.review&&<> 교사 확인 {formatTime(t.havruta.review.at)} · {havrutaLabel(t)}</>}</p>}{onScope&&<button className="task-scope-trigger" type="button" disabled={!!t.cancelled} aria-label={t.title+' 배정 범위 수정'} onClick={onScope}>교재·단원·쪽수 선택</button>}{t.range&&<p>{t.range}</p>}{t.unresolved&&<p className="attention-text">미해결 · {t.unresolved}</p>}{event.class_date!==t.workDate&&<p className="hint">{event.class_date} 수업에서 이어온 일</p>}<div className="task-actions">{(['working','student_done','check','done'] as const).map(state=><button key={state} aria-pressed={havrutaState(t)===state} disabled={havrutaState(t)!==state&&!canUndo('state:'+state)&&(state==='working'||state==='done')&&!!blocked} title={t.state===state?'다시 눌러 취소':undefined} onClick={()=>stateTap(state)}>{state==='done'&&<Check size={16}/>}{t.havruta?{working:'협동 풀이',student_done:'설명 요청',check:'다시 설명',done:'설명 확인·통과'}[state]:{working:'진행',student_done:'학생 마침',check:'확인 필요',done:'확인 마침'}[state]}</button>)}</div>{blocked&&<p className="hint">선행 활동을 마치거나 상세에서 순서 변경 이유를 남겨 주세요.</p>}
 <ActivityTimingControls timing={t.timing} undoKey={canUndo('timing:set')?'set':canUndo('timing:visit')?'visit':''} onTap={(key,timing)=>toggle('timing:'+key,{timing})} disabled={['done','skipped','pending'].includes(havrutaState(t))} change={timing=>control({timing})}/><details><summary>범위·점검·남은 일</summary><div className="detail-fields"><label>교재·범위<input value={t.range} onChange={e=>change({range:e.target.value,scope:undefined})} placeholder="교재명 · 단원 / 페이지 / 문항" maxLength={2000}/></label><Pick label="활동 담당" value={t.lane} onChange={v=>control({lane:v as Task['lane']})} items={[["student","학생 활동"],["teacher","강사 진행·확인"]]}/><Field label="활동 메모" value={t.note} onChange={note=>change({note})}/><div className="field-grid"><Field label="시도한 범위" value={t.attempted} onChange={attempted=>change({attempted})} max={2000}/><Field label="채점한 내용" value={t.marked} onChange={marked=>change({marked})} max={2000}/><Field label="오답 재확인" value={t.corrected} onChange={corrected=>change({corrected})} max={2000}/><Field label="아직 해결하지 못한 일" value={t.unresolved} onChange={unresolved=>change({unresolved})} max={2000}/></div>
 <fieldset><legend>직접 점검한 자료</legend>{['개념서','필기 노트','풀이 노트'].map(m=><Tick key={m} checked={t.materials.includes(m)} onChange={v=>control({materials:v?[...t.materials,m]:t.materials.filter(x=>x!==m)})}>{m}</Tick>)}</fieldset><Tick checked={!!t.inspectedAt} onChange={v=>control({inspectedAt:v?new Date().toISOString():''})}>자료 점검 마침 {formatTime(t.inspectedAt)}</Tick><Tick checked={!!t.feedbackAt} onChange={v=>control({feedbackAt:v?new Date().toISOString():''})}>학생에게 피드백 전달함 {formatTime(t.feedbackAt)}</Tick>
 <Pick label="선행 관계" value={t.relation} onChange={v=>control({relation:v as Task['relation']})} items={[["independent","독립적으로 진행"],["recommended","먼저 하면 좋은 활동 있음"],["required","먼저 확인해야 할 활동 있음"]]}/>{t.relation!=='independent'&&<><Pick label="선행 활동" value={t.prerequisite} onChange={prerequisite=>control({prerequisite})} items={[["","선행 활동 선택"],...all.filter(e=>e.entity_id!==event.entity_id).map(e=>[e.entity_id,JSON.parse(e.body).title+' · '+e.class_date+(JSON.parse(e.body).cancelled?' · 삭제됨':'')] as [string,string])]}/><Field label="순서를 바꿔 진행한 이유 (필요할 때)" value={t.overrideReason} onChange={overrideReason=>change({overrideReason})} max={2000}/></>}
 <div className="task-actions"><button aria-pressed={t.state==='pending'} onClick={()=>stateTap('pending')}>남은 일로 보관{t.state==='pending'?' · 취소':''}</button><button aria-pressed={t.state==='skipped'} onClick={()=>stateTap('skipped')}>이번에는 생략{t.state==='skipped'?' · 취소':''}</button></div><p className="hint">활동 확인을 마쳐도 이해 완료나 정답 처리를 뜻하지 않습니다. 미해결 내용은 함께 남길 수 있습니다.</p><button className="quiet" onClick={()=>void fetch('/api/classroom?entity='+event.entity_id).then(async r=>{if(!r.ok)throw new Error('연결 후 이력을 확인해 주세요.');setHistory((await r.json() as {ledger:ClassEvent[]}).ledger);}).catch(fail)}>이 활동의 변경 이력</button>{history&&history.map(e=>{const b=JSON.parse(e.body);return <div className="history" key={e.id}><b>{e.created_at.slice(0,10)} {formatTime(e.created_at)} · {b.cancelled?'삭제·배정 취소':b.havruta?havrutaLabel(b):taskLabels[b.state as Task['state']]}</b><p>배정일 {b.workDate} · {b.range||'범위 미입력'}</p><p>{b.note} {b.unresolved&&'미해결: '+b.unresolved}</p>{b.timing&&<p>배정 {formatTime(b.timing.assignedAt)||'미기록'} · 방문 {formatTime(b.timing.visitedAt)||'미표시'} · 다시 보기 {formatTime(b.timing.revisitAt)||'미지정'}</p>}</div>})}</div></details></SwipeDeleteCard>;
}

export function PendingTaskCard({event,date,save,fail}:{event:ClassEvent;date:string;save:Save;fail:(e:unknown)=>void}){
 const [t,,,,commit]=useForm(values(event,task('',event.class_date)),(v,b,mode)=>save('activity',event.entity_id,v,event.class_date,b,mode),fail,event.id);
 return <SwipeDeleteCard label={t.title} revision={event.id+JSON.stringify(t)} className="pending-swipe" deleted={!!t.cancelled} onDelete={()=>commit({cancelled:true})} onRestore={()=>commit({cancelled:false})} onError={fail} heading={<span><strong>{t.title}</strong><span className="pending-description">{t.unresolved||t.note||t.range||(t.havruta?havrutaLabel(t):taskLabels[t.state])}</span><small>원수업 {event.class_date} · 마지막 배정 {t.workDate}</small></span>}><button onClick={()=>void commit({workDate:date,state:'assigned',timing:assignedTiming(),...(t.havruta?{havruta:{...t.havruta,review:null}}:{})}).catch(fail)}>오늘 이어서 <ArrowRight size={16}/></button></SwipeDeleteCard>;
}

export function CloseoutPanel({studentId,date,ledger,roster=students,data,save,retainReview,fail,copy,allowAnalysis=false,onTracker}:{studentId:string;date:string;ledger:ClassEvent[];roster?:Student[];data?:NotebookData;save:Save;retainReview?:(sessionId:string,text:string)=>Promise<void>;fail:(e:unknown)=>void;copy:(s:string)=>void;allowAnalysis?:boolean;onTracker?:()=>void}){
 const e=ledger.find(e=>e.entity_id===entity('closeout',studentId,date));
 const [c,put,tap,,commit]=useForm(values(e,blankCloseout),(v,b,mode)=>save('closeout',entity('closeout',studentId,date),v,date,b,mode),fail,e?.id||'');
 const basis=data?closeoutEvidenceBasis(studentId,date,data):'',current=closeoutCurrent(c,basis);
 const change=(p:Partial<Closeout>,mode:RevisionMode='draft')=>{const homeworkChanged=['homework','due','noHomework'].some(k=>k in p);put({...p,...(homeworkChanged?{homeworkPlan:undefined,parentInput:undefined,...(c.diary?{diary:{...c.diary,homework:''}}:{})}:{}),confirmed:false},mode);};
 const [performed,setPerformed]=useState<string[]>([]);
 const performedCandidates=ledger.filter(e=>{if(e.student_id!==studentId||e.kind!=='activity')return false;const t=JSON.parse(e.body) as Task;return t.workDate===date&&!t.cancelled&&!['assigned','skipped'].includes(t.state);});
 function prepareDiary(){try{const input=parentInputFromClass(studentId,date,ledger,performed,c,e?.id||entity('closeout',studentId,date)),preview=previewParentDiary(input);change({progress:preview.fields.progress,parentInput:input,diary:{...preview.fields,classMemo:c.diary?.classMemo||preview.fields.classMemo}},'event');}catch(error){fail(error);}}
 const [analysis,setAnalysis]=useState<{state:string;message:string;requestId?:string}>({state:'idle',message:''});
 const analyzing=useRef(false);
 async function analyze(reanalyseFrom?:string){
  if(analyzing.current||!data||!allowAnalysis)return;analyzing.current=true;
  setAnalysis({state:'running',message:'Native Hermes 분석 요청 중 · 다른 학생 화면으로 이동해도 원래 학생에 보관합니다.'});
  try{
   const response=await fetch('/api/closeout-analysis',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({studentId,date,basis,...(reanalyseFrom?{reanalyseFrom}:{})}),signal:AbortSignal.timeout(240000)});
   const result=await response.json() as {state?:string;message?:string;error?:string;requestId?:string};
   setAnalysis({state:result.state||'blocked',message:result.message||result.error||'분석 결과를 확인하지 못했습니다. 자동 재시도하지 않습니다.',requestId:result.requestId});
  }catch{setAnalysis({state:'unknown',message:'연결이 끊겨 Native 실행 결과가 불명확합니다. 저장된 요청·초안을 먼저 확인하며 자동 재시도하지 않습니다.'});}
  finally{analyzing.current=false;}
 }
 return <details className={'panel closeout '+(current?'confirmed':'')}>
  <summary className="closeout-summary"><span>진도·숙제 최종 검토</span><span className={'status-tag '+(current?'complete':'attention')}>{current?'확정함':c.confirmed?'근거 변경 · 다시 확정':'확정 필요'}</span></summary>
  {allowAnalysis&&<button className="primary" disabled={!data||analysis.state==='running'} onClick={()=>void analyze()}>수업 후 근거 정리</button>}
  {analysis.message&&<p className="hint" role="status">{analysis.message}</p>}
  {analysis.state==='changed'&&analysis.requestId&&<button onClick={()=>void analyze(analysis.requestId)}>새 근거로 Native 분석 1회 요청</button>}
  {c.confirmed&&!current&&<p className="notice" role="status">근거 변경 · 다시 확정이 필요합니다. 이전 확정과 귀가 사실은 보존되며 상세 기록 전달만 중지합니다.</p>}
  {data&&<CloseoutCandidates studentId={studentId} date={date} sessions={data.sessions} events={data.events} review={retainReview?{current:c,basis,apply:next=>commit(next),retain:retainReview}:undefined}/>}
  {roster.find(s=>s.id===studentId)&&<details className="closeout-homework"><summary>다음 수업 숙제 · 교재·범위로 선택</summary><HomeworkPanel key={studentId+':'+date} student={roster.find(s=>s.id===studentId)!} date={date} ledger={ledger} snapshot={data?.sheet?.snapshot} save={save} fail={fail} closeout={c} onSave={next=>commit(next)}/></details>}
  <p className="homework-summary">{c.noHomework?'다음 수업 전 숙제 없음':c.homework?(c.due+'까지 · '+c.homework):'다음 수업 숙제를 먼저 선택하세요.'}</p>
  <details><summary>기존 진도·숙제 원문 직접 수정</summary><Field label="오늘 실제 진도" value={c.progress} onChange={progress=>change({progress})} placeholder="교재명 · 단원 · 실제 확인한 페이지/문항"/>
  <Tick checked={c.noHomework} onChange={noHomework=>change({noHomework},'event')}>다음 숙제 없음으로 확인</Tick>
  {!c.noHomework&&<><Field label="다음 숙제의 교재·범위" value={c.homework} onChange={homework=>change({homework})} placeholder="교재명 · 단원 · 페이지/문항"/><label className="field">숙제 기한<input type="date" value={c.due} onChange={e=>change({due:e.target.value},'event')}/></label></>}
  </details><details><summary>교사만 보는 다음 확인</summary><Field label="다음 만남에서 확인할 내용" value={c.next} onChange={next=>change({next})}/></details>
  <section className="diary-fields" aria-label="학원 공개 일지 검토"><h3>학원 일지 · 각 200자</h3><p className="hint">오늘 실제 수행한 활동·범위를 확인해 선택하세요. 일부만 했다면 활동 상세의 실제 범위를 먼저 수정합니다. 배정만 한 활동은 포함하지 않습니다.</p>
  <div className="parent-performed">{performedCandidates.map(e=>{const t=JSON.parse(e.body) as Task;return <label key={e.id} className="checkbox-label"><input type="checkbox" checked={performed.includes(e.id)} onChange={event=>setPerformed(event.target.checked?[...performed,e.id]:performed.filter(id=>id!==e.id))}/><span>{t.title} · {t.attempted||t.range||(t.scope?scopeText(t.scope):'범위 미기록')}<small>이 실제 수행 범위를 확인함</small></span></label>;})}</div>
  {!performedCandidates.length&&<p className="hint">기록된 수행 활동이 없습니다. 수행하지 않았다는 뜻은 아닙니다. 실제 활동을 보완하거나 공개 진도를 직접 작성하세요.</p>}
  <button disabled={!performed.length} onClick={prepareDiary}>활동으로 200자 일지 초안</button><p className="hint">고정 양식으로 진도·다음 숙제를 묶습니다. 기존 공개 메모는 유지하며 원음·내부 메모는 복사하지 않습니다.</p>
  {(['progress','homework','classMemo'] as const).map(key=>{const v=(c.diary||blankDiary)[key],limit=diaryLimit(v);return <div key={key}><Field label={{progress:'학원 공개 진도',homework:'학원 공개 숙제',classMemo:'학원 공개 메모 (선택)'}[key]} value={v} onChange={raw=>{const text=raw.replace(/\r\n|\r|\n/g,'\r\n');change({...(key==='progress'?{progress:text}:{}),diary:{...(c.diary||blankDiary),[key]:text} as PublicDiary});}}/><small className={'diary-count '+(!limit.valid?'over':'')}>{limit.characters}/200자 · 학원 길이 {limit.legacyLength}/400{!limit.valid?' · 전체 초안을 보존했습니다. 의미를 확인하며 줄여 주세요.':''}</small></div>;})}
  <p className="hint">활동 배정·학생 마침·교사 통과는 서로 다릅니다. 학원 DB 입력 후 학생 리포트 저장·학부모 발송은 선생님이 별도로 합니다.</p></section>
  <div className="button-row"><button className="primary" aria-pressed={current} disabled={!current&&(!completeCloseout(c)||!!c.diary&&!diaryReady(c.diary))} onClick={()=>tap('confirm:'+basis,{confirmed:!current,evidenceBasis:basis})}><ClipboardCheck size={18}/>{current?'진도·숙제 확정 취소':c.confirmed?'최신 근거로 다시 확정':'진도·숙제 확정'}</button></div><p className="hint">안내·귀가는 수업 중 카드에서 별도로 기록합니다. 이 확정은 상세 학생 기록을 전달하기 위한 검토입니다.</p>
  {data&&(JSON.stringify(values(e,blankCloseout))===JSON.stringify(c)?<RecordProgress view={classroomView(studentId,date,{...data,ledger})} onTracker={onTracker}/>:<p className="pending-record" role="status">최신 입력 보관 결과를 확인하는 중입니다. 원본 반영과는 별개입니다.</p>)}
  <AcademyPanel key={studentId+':'+date+':'+(e?.id||'')} studentId={studentId} date={date} entryId={e?.id} ready={!!e&&!data?.localItems?.some(item=>item.payload?.id===e.id&&['job','draft'].includes(item.type))&&!data?.rehearsalId&&current&&!!c.diary&&diaryReady(c.diary)&&JSON.stringify(values(e,blankCloseout))===JSON.stringify(c)}/>
  <div className="handoff"><button disabled={!current||!e||JSON.stringify(values(e,blankCloseout))!==JSON.stringify(c)} onClick={()=>{try{copy(trackerHandoff(studentId,date,ledger,roster,false,!!data?.rehearsalId));}catch(error){fail(error);}}}><Copy size={17}/>Tracker 전달 내용 복사</button><p className="hint">Tracker의 수업 후 검토 → 아이폰 확정 내용 가져오기에 붙여 넣으세요. 학생·수업일과 진도·숙제를 대조한 뒤 반영합니다.</p></div>
  <p className="hint">수정하면 다시 확정합니다. 교재별 확인 쪽수와 출결은 Tracker에서 기록하세요.</p>
 </details>;
}

export function ReviewPanel({studentId,date,data,save,fail,copy,onSource}:{studentId:string;date:string;data:NotebookData;save:Save;fail:(e:unknown)=>void;copy:(s:string)=>void;onSource:(id:string)=>void}){
 const roster=data.roster||students,student=roster.find(s=>s.id===studentId)||{name:studentId},ledger=data.ledger.filter(e=>e.student_id===studentId),e=ledger.find(e=>e.entity_id===entity('report',studentId,date));const savedClose=values(ledger.find(e=>e.entity_id===entity('closeout',studentId,date)),blankCloseout),close={...savedClose,confirmed:closeoutCurrent(savedClose,closeoutEvidenceBasis(studentId,date,data))};const basis=reviewBasis(studentId,date,data.ledger,data.sessions,data.events);
 const [r,put,tap,canUndo]=useForm(values(e,blankReport),(v,b,mode)=>save('report',entity('report',studentId,date),v,date,b,mode),fail,e?.id||''),[checkedValue,setCheckedValue]=useState<string|null>(null);const checkKey=reportCheckKey(r,basis,close.confirmed),checked=checkedValue===checkKey,setChecked=(value:boolean)=>setCheckedValue(value?checkKey:null);const change=(p:Partial<Report>)=>{setChecked(false);put({...p,confirmed:false,transferredAt:''});};const current=r.confirmed&&r.basis===basis,parentKey='parent:'+basis,parentReady=current&&!!r.parent.trim();const ss=data.sessions.filter(s=>s.student_id===studentId&&!isTest(s));const tasks=ledger.filter(e=>e.kind==='activity'&&(JSON.parse(e.body).workDate===date||isOpen(JSON.parse(e.body))));
 return <div className="review-workspace"><div className="review-draft-column">
 <details className="panel review-draft"><summary>다른 도구에서 만든 초안 · 선택 사항</summary><p className="hint">위에서 보관된 근거와 초안을 먼저 검토하세요. 별도로 정리한 글이 있을 때만 여기에 남깁니다.</p><Field label="별도로 정리한 초안" value={r.draft} onChange={draft=>change({draft})} max={100000}/></details>
 <section className="panel teacher-review"><h3>강사 보완·수업 검토</h3><Field label="확인한 내용" value={r.summary} onChange={summary=>change({summary})}/><Field label="미확인·다시 확인할 내용 (강사 메모)" value={r.needs} onChange={needs=>change({needs})}/><Field label="다음 수업에서 할 일" value={r.next} onChange={next=>change({next})}/>
 <Tick checked={checked} onChange={setChecked}>원문·관찰·진도·숙제를 대조했습니다.</Tick><button className="primary" aria-pressed={r.confirmed} disabled={!r.confirmed&&(!checked||!close.confirmed||!r.summary.trim())} onClick={()=>{tap(reportConfirmationKey(r,basis),{confirmed:!r.confirmed,basis:r.confirmed?'':basis,transferredAt:''});setChecked(false);}}><Check size={18}/>{r.confirmed?'교사 검토 확정 취소':'이 내용으로 교사 검토 확정'}</button>{!close.confirmed&&<p className="attention-text">상세 기록 전달 전 진도·숙제를 먼저 확정해 주세요.</p>}{r.confirmed&&!current&&<p className="attention-text">검토 이후 근거가 바뀌었습니다. 최신 내용을 대조하고 다시 확정해 주세요.</p>}
 <div className="handoff"><button disabled={!close.confirmed} onClick={()=>{try{copy(trackerHandoff(studentId,date,data.ledger,roster,false,!!data.rehearsalId));}catch(error){fail(error);}}}>Tracker 전달 내용 복사</button></div></section>
 <details className="panel parent-message"><summary>학부모 문안·실제 전송 기록</summary><button aria-pressed={canUndo(parentKey)} disabled={!close.confirmed&&!canUndo(parentKey)} onClick={()=>tap(parentKey,{parent:`${date} ${student.name} 수업 안내\n\n오늘 확인한 진도: ${close.progress}\n다음 숙제: ${close.noHomework?'없음':close.homework+' (기한 '+close.due+')'}${close.next?'\n다음 확인: '+close.next:''}`,transferredAt:''})}>{canUndo(parentKey)?'문안 시작 취소 · 이전 글 복원':'확정한 진도로 문안 시작'}</button><Field label="학부모 리포트 문안" value={r.parent} onChange={parent=>put({parent,transferredAt:''})} placeholder="학부모에게 전달할 사실과 안내를 검토하세요."/>
 <div className="handoff"><button disabled={!parentReady} onClick={()=>copy(r.parent)}><Copy size={17}/>학부모 문안 복사</button><Tick checked={!!r.transferredAt&&parentReady} onChange={v=>{if(parentReady)put({transferredAt:v?new Date().toISOString():''},'event');}}>학원 사이트에서 전송을 마쳤음 (직접 표시)</Tick><p className="hint">문안을 확인한 뒤 학원 사이트에서 전송하세요. 복사는 전송이 아닙니다.</p></div></details></div><aside className="review-evidence" aria-label="수업 검토 근거"><section className="panel"><div className="section-title"><h3>{student.name} · {classPart(studentId,date,roster)} 검토</h3><span className={'status-tag '+(!current?'attention':'')}>{current?'현재 근거 검토함':r.confirmed?'근거 변경 · 재검토 필요':'교사 검토 전'}</span></div><dl className="facts"><dt>실제 진도 {close.confirmed?'· 확정':'· 미확정'}</dt><dd>{close.progress||'미확인'}</dd><dt>다음 숙제</dt><dd>{close.noHomework?'없음으로 확인':`${close.homework||'미확인'} · 기한 ${close.due||'미확인'}`}</dd><dt>다음 확인</dt><dd>{close.next||'기록 없음'}</dd></dl><h4>활동·미해결 근거</h4>{tasks.map(e=>{const t=JSON.parse(e.body) as Task;return <p key={e.entity_id}><b>{t.title}</b> · {t.cancelled?'배정 취소':t.havruta?havrutaLabel(t):taskLabels[t.state]} · {t.range||'범위 미입력'}{t.unresolved&&` · 미해결 ${t.unresolved}`} <small>원수업 {e.class_date}</small></p>})}
 <h4>대화별 관찰·원문</h4>{ss.map(s=>{const es=data.events.filter(e=>e.session_id===s.id),o=parse(latest(es,'observation'));return <article className="source-summary" key={s.id}><b>{formatTime(s.created_at)} · {s.title}</b><p>직접 관찰 · {o.observed||'기록 없음'}</p><p>학생 자기보고 · {o.studentSaid||'기록 없음'}</p><p>다음 확인 · {o.next||'기록 없음'}</p>{cardRevisions(es).filter(r=>!r.card.deleted).map(r=><p key={r.card.cardId}><b>{{observed:'직접 관찰',studentSaid:'학생 자기보고',next:'다음 확인'}[r.card.category]}</b> · {r.card.text}<br/><span className="hint">{r.card.scene.activity} {r.card.scene.range}{r.card.occurrenceOf?' · 다시 관찰한 별도 기록':''}</span></p>)}<button onClick={()=>onSource(s.id)}>이 대화의 원문 확인 <ArrowRight size={16}/></button></article>})}{!ss.length&&<p className="empty-small">실제 수업 대화 기록이 없습니다. 테스트는 제외됩니다.</p>}</section></aside></div>;
}
