'use client';
import {useEffect,useLayoutEffect,useRef,useState,useSyncExternalStore} from 'react';
import {Mic,Download,Settings2,RefreshCw,ArrowUpRight,CloudUpload,Headphones,ClipboardList,FileCheck,ShieldCheck} from 'lucide-react';
import {Tabs,TabsContent,TabsList,TabsTrigger} from '@/components/ui/tabs';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {students as initialStudents,scheduled,initialDate,SOURCE_DATE,SHEET_URL,latest,parse,type Entry} from '@/lib/notebook';
import {blankReport,classPart,classTime,entity,exportClass,isTest,reviewBasis,sourceLesson,values,type Task,type ClassEvent} from '@/lib/classroom';
import {notebookDestination} from '@/lib/handoff';
import {DeviceOutbox,jobDependencies,type LocalItem,type Mutation,type RevisionMode} from '@/lib/outbox';
import {isCardKind} from '@/lib/observation-cards';

import {ClassroomBoard} from './classroom-board';
import {QuickWork} from './quick-work';
import {RecorderDock} from './recorder-dock';
import {NativeCapture,type NativeCaptureTarget} from './native-capture';
import {transferReturnTarget} from '@/lib/audio-transfer-model';
import {DatasetPanel} from './dataset-panel';
import {SheetPanel} from './sheet-panel';
import {ObservationCards} from './observation-cards';
import {ConversationCandidates} from './conversation-candidates';
import {ConversationList} from './conversation-list';
import {WebMCPRead} from './webmcp-read';
import {markCurrentActivityStudentDone,type LessonSnapshot,type StudentDoneInput,type ToolResult} from '@/lib/webmcp';
import {ClassRecorder,idleRecording,pcmWav,type RecordStatus} from '@/lib/recorder';
import {emptyData,projectData,type NotebookData} from '@/lib/projection';
import {classroomView,type SheetObservation} from '@/lib/classroom-view';
import {Activities,CloseoutPanel,Observation,Pick,ReviewPanel,Tick,formatTime} from './classroom-panels';

import {post} from '@/lib/client-api';
import {assignedBooks,catalogFromSnapshot} from '@/lib/curriculum';
export {post} from '@/lib/client-api';
function download(name:string,value:string|Uint8Array,mime='text/plain;charset=utf-8'){const url=URL.createObjectURL(new Blob([value as BlobPart],{type:mime}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),10000);}
type RecordingIntent={studentId:string;date:string;sessionId:string;title:string;purpose:string;newConversation?:boolean};
type Target={sessionId:string;studentId:string;date:string;captureId:string};
function recordingRequest(choice:RecordingIntent,data:NotebookData,target:Target|null):RecordingIntent{
 const chosen=data.sessions.find(s=>s.id===choice.sessionId&&s.student_id===choice.studentId&&!s.ended_at)||(!choice.newConversation?data.sessions.filter(s=>s.student_id===choice.studentId&&s.class_date===choice.date&&!s.ended_at&&(isTest(s)?'test':'lesson')===choice.purpose).at(-1):undefined);
 const pinned=target?.sessionId===choice.sessionId&&!data.sessions.some(s=>s.id===choice.sessionId&&s.ended_at)?choice.sessionId:'';
 return {...choice,sessionId:chosen?.id||pinned,purpose:chosen?.purpose||choice.purpose};
}
function prerequisiteDependencies(value:unknown,ledger:ClassEvent[]){const id=(value as Partial<Task>|null)?.prerequisite;const entry=typeof id==='string'&&id?ledger.find(e=>e.entity_id===id):undefined;return entry?[entry.id]:[];}
function objectValue(value:unknown):Record<string,unknown>{return value&&typeof value==='object'&&!Array.isArray(value)?value as Record<string,unknown>:{};}
function subscribeOpacity(notify:()=>void){window.addEventListener('storage',notify);window.addEventListener('spt-opacity',notify);return()=>{window.removeEventListener('storage',notify);window.removeEventListener('spt-opacity',notify);};}
function readOpacity(){try{return localStorage.getItem('spt-opaque')==='true';}catch{return false;}}
function setOpaque(value:boolean){try{localStorage.setItem('spt-opaque',String(value));}catch{}window.dispatchEvent(new Event('spt-opacity'));}
export default function Notebook({ownerKey,rehearsalId,rehearsalDate}:{ownerKey:string;rehearsalId?:string;rehearsalDate?:string}){
 const [date,setDate]=useState(()=>rehearsalDate||initialDate()),[studentId,setStudentId]=useState(()=>scheduled(rehearsalDate||initialDate())[0]?.id||initialStudents[0].id),[tab,setTab]=useState('class'),[scope,setScope]=useState('1부'),[all,setAll]=useState(false),[tests,setTests]=useState(false),[sessionId,setSessionId]=useState(''),[title,setTitle]=useState(''),[purpose,setPurpose]=useState('lesson');
 const [base,setBase]=useState<NotebookData>(emptyData),[items,setItems]=useState<LocalItem[]>([]),[ready,setReady]=useState(false),[online,setOnline]=useState(true),[error,setError]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[syncMessage,setSyncMessage]=useState(''),[status,setStatus]=useState<RecordStatus>(idleRecording),[target,setTarget]=useState<Target|null>(null),[partial,setPartial]=useState(''),[settings,setSettings]=useState(false),[key,setKey]=useState(''),[queueOpen,setQueueOpen]=useState(false),[conflict,setConflict]=useState<{job:LocalItem;server:Record<string,unknown>;baseId:string}|null>(null),[compareChecked,setCompareChecked]=useState(false);
 const [dockChoice,setDockChoice]=useState<RecordingIntent>(()=>({studentId:'',date,sessionId:'',title:'',purpose:'lesson'})),[dockPicker,setDockPicker]=useState(false),[dockEnding,setDockEnding]=useState<RecordingIntent|null>(null);
 const recordingTransition=useRef(false),generation=useRef(0),selectedRef=useRef(studentId),captureTarget=useRef<Target|null>(null);
 const box=useRef<DeviceOutbox|null>(null),recorder=useRef<ClassRecorder|null>(null),day=useRef(date),baseRef=useRef(base),dataRef=useRef(emptyData),refreshing=useRef(false);
 const [syncedAt,setSyncedAt]=useState(''),[serverIssue,setServerIssue]=useState(false),[sourceReturn,setSourceReturn]=useState<number|null>(null),[deviceOutbox,setDeviceOutbox]=useState<DeviceOutbox|null>(null),[hasEmergency,setHasEmergency]=useState(false);
 const opaque=useSyncExternalStore(subscribeOpacity,readOpacity,()=>false);
 const [nativeTarget,setNativeTarget]=useState<NativeCaptureTarget|null>(null);
 useEffect(()=>{document.documentElement.dataset.transparency=opaque?'reduced':'normal';},[opaque]);
 const data={...projectData(base,items,date),rehearsalId,localItems:items};
 const visitKey=studentId+':'+date,[tabVisits,setTabVisits]=useState({key:visitKey,tabs:[tab]});
 if(tabVisits.key!==visitKey){setTabVisits({key:visitKey,tabs:[tab]});}else if(!tabVisits.tabs.includes(tab)){setTabVisits({...tabVisits,tabs:[...tabVisits.tabs,tab]});}
 useLayoutEffect(()=>{selectedRef.current=studentId;day.current=date;baseRef.current=base;dataRef.current=data;});
 const sourceReturnFocus=useRef<HTMLElement|null>(null);
 const curriculum=catalogFromSnapshot(data.sheet?.snapshot);
 const students=(data.roster||initialStudents).map(s=>{const books=curriculum?assignedBooks(curriculum,s.id).map(b=>b.name):[];return books.length?{...s,books}:s;});
 const student=students.find(s=>s.id===studentId)||{id:studentId,name:studentId,days:[],part:'',time:'',firstDate:'',books:[]},active=['preparing','recording','stopping'].includes(status.phase),pending=items.filter(x=>['draft','job','audioDraft'].includes(x.type)),failures=pending.filter(x=>x.error);
 const roster=all?students:scheduled(date,students),sessions=data.sessions.filter(s=>s.student_id===studentId&&s.class_date===date&&(tests||!isTest(s))),session=sessions.find(s=>s.id===sessionId),events=data.events.filter(e=>e.session_id===sessionId),caps=data.captures.filter(c=>c.session_id===sessionId);
 const fail=(e:unknown)=>setError(e instanceof Error?e.message:'처리하지 못했습니다. 입력은 유지합니다.');
 async function refresh(dayValue=day.current){
  if(refreshing.current)return;refreshing.current=true;const started=Date.now();
  try{
   const [nResponse,cResponse,sheet]=await Promise.all([
    fetch('/api/notebook?date='+dayValue,{cache:'no-store',signal:AbortSignal.timeout(12000)}),
    fetch('/api/classroom',{cache:'no-store',signal:AbortSignal.timeout(12000)}),
    fetch('/api/sheet?date='+dayValue,{cache:'no-store',signal:AbortSignal.timeout(12000)}).then(async r=>r.ok?{...await r.json(),date:dayValue} as SheetObservation:undefined).catch(()=>undefined),
   ]);
   if(!nResponse.ok||!cResponse.ok)throw new Error('서버 기록을 불러오지 못했습니다. 이 기기의 기록을 표시합니다.');
   const [n,c]=await Promise.all([nResponse.json(),cResponse.json()]) as [NotebookData&{ownerKey:string},{ledger:ClassEvent[]}];
   if(n.ownerKey!==ownerKey)throw new Error('로그인 계정이 바뀌었습니다. 이 기록장을 다시 열어 주세요.');
   const next:NotebookData={...n,ledger:c.ledger,sheet,classroomLoaded:true};
   await box.current?.cache('roster',{students:next.roster,revision:next.rosterRevision,source:next.rosterSource});await box.current?.cache('day:'+dayValue,next);
   await box.current?.reconcile(started,[...next.sessions.map(s=>s.id),...next.captures.map(c=>c.id)],next.events.map(e=>e.id));
   if(dayValue===day.current){baseRef.current=next;setBase(next);setSyncedAt(new Date().toISOString());setServerIssue(false);}return next;
  }catch(e){if(dayValue===day.current)setServerIssue(true);setSyncMessage(e instanceof Error?e.message:'연결을 확인해 주세요.');}finally{refreshing.current=false;}
 }
 const destinationApplied=useRef(false);
 const [fieldFocus,setFieldFocus]=useState(false);
 useEffect(()=>{if(destinationApplied.current||!ready||active)return;const target=notebookDestination(window.location.search,students);if(!target||rehearsalDate&&target.date!==rehearsalDate)return;let disposed=false;const restore=async()=>{await box.current?.read();const importId=new URLSearchParams(window.location.search).get('audioImport');let returned:NativeCaptureTarget|null=null;if(importId){const r=await fetch('/api/audio-import?id='+encodeURIComponent(importId),{cache:'no-store'});if(!r.ok)throw new Error('전송한 녹음의 원래 대상을 불러오지 못했습니다.');returned=transferReturnTarget(window.location.search,await r.json());}if(disposed||destinationApplied.current)return;if(returned)setNativeTarget(returned);setFieldFocus(target.view!=='class');destinationApplied.current=true;day.current=target.date;setDate(target.date);setSyncedAt('');setServerIssue(false);setStudentId(target.studentId);setTab(target.view);setScope(classPart(target.studentId,target.date,students));setAll(!scheduled(target.date,students).some(s=>s.id===target.studentId));setBase({...emptyData,...box.current?.cached<NotebookData>('day:'+target.date),classroomLoaded:!!box.current?.cached<NotebookData>('day:'+target.date)&&box.current?.cached<NotebookData>('day:'+target.date)?.classroomLoaded!==false,roster:students,rosterRevision:data.rosterRevision,rosterSource:data.rosterSource});void refresh(target.date);};void restore().catch(fail);return()=>{disposed=true;};},[ready,data.rosterRevision,active]);
 useEffect(()=>{let disposed=false;const outbox=new DeviceOutbox(ownerKey+(rehearsalId?':rehearsal:'+rehearsalId:''),ownerKey);box.current=outbox;const update=()=>{if(disposed)return;setItems([...outbox.items]);setSyncMessage(outbox.message);};const unsubscribe=outbox.subscribe(update);
  const sync=async()=>{if(disposed)return;try{await outbox.recover();await outbox.flush();await refresh();}catch(e){if(!disposed)fail(e);}};
  void outbox.read().then(async()=>{if(disposed)return;const cached=outbox.cached<NotebookData>('day:'+day.current),catalog=outbox.cached<{students:NotebookData['roster'];revision?:string;source?:NotebookData['rosterSource']}>('roster');if(cached||catalog)setBase({...emptyData,...cached,classroomLoaded:!!cached&&cached.classroomLoaded!==false,...(catalog?{roster:catalog.students,rosterRevision:catalog.revision,rosterSource:catalog.source}:{})});setDeviceOutbox(outbox);setReady(true);await sync();}).catch(fail);
  const interval=setInterval(()=>void sync(),5000),connection=()=>{setOnline(navigator.onLine);if(navigator.onLine)void sync();};connection();window.addEventListener('online',connection);window.addEventListener('offline',connection);
  const visibility=()=>{if(document.visibilityState==='visible')void sync();};document.addEventListener('visibilitychange',visibility);
  const unload=(e:BeforeUnloadEvent)=>{if(recorder.current?.isRecording||recorder.current?.emergency||outbox.hasUnstoredNotes){e.preventDefault();e.returnValue='';}};window.addEventListener('beforeunload',unload);
  return()=>{disposed=true;void recorder.current?.stop(true);unsubscribe();clearInterval(interval);window.removeEventListener('online',connection);window.removeEventListener('offline',connection);document.removeEventListener('visibilitychange',visibility);window.removeEventListener('beforeunload',unload);};
 },[ownerKey,rehearsalId]);
 useEffect(()=>{if(!ready)return;let running=false;const syncSheet=async()=>{if(running||!navigator.onLine)return;running=true;try{await fetch('/api/sheet',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'auto',date:day.current}),signal:AbortSignal.timeout(110000)});}catch{}finally{running=false;}};void syncSheet();const timer=setInterval(()=>void syncSheet(),60000);return()=>clearInterval(timer);},[ready]);
 useEffect(()=>{if(!ready)return;const t=setTimeout(()=>void box.current?.flush().catch(fail),900);return()=>clearTimeout(t);},[items.filter(x=>x.type==='draft').map(x=>x.payload?.id+JSON.stringify(x.payload?.data)).join('|'),ready]);
 function choose(id:string){fieldOrigin.current=typeof document==='undefined'?null:document.getElementById('field-student-'+id)?.getBoundingClientRect?.()||null;setFieldFocus(true);destinationApplied.current=true;if(id!==selectedRef.current){setSourceReturn(null);setStudentId(id);setSessionId(dataRef.current.sessions.filter(s=>s.student_id===id&&!s.ended_at&&!isTest(s)).at(-1)?.id||'');setTitle('');setPurpose('lesson');}requestAnimationFrame(()=>{document.getElementById('student-work')?.scrollIntoView({block:'start',behavior:'instant'});document.getElementById('student-heading')?.focus({preventScroll:true});});}
 async function changeDate(value:string){if(!value||active)return;setFieldFocus(false);destinationApplied.current=true;day.current=value;setDate(value);setSyncedAt('');setServerIssue(false);setSourceReturn(null);setBase({...emptyData,...box.current?.cached<NotebookData>('day:'+value),classroomLoaded:!!box.current?.cached<NotebookData>('day:'+value)&&box.current?.cached<NotebookData>('day:'+value)?.classroomLoaded!==false,roster:students,rosterRevision:data.rosterRevision,rosterSource:data.rosterSource});setStudentId(scheduled(value,students)[0]?.id||students[0]?.id||studentId);setScope(classPart(scheduled(value,students)[0]?.id||studentId,value,students));setSessionId('');setTitle('');await refresh(value);}
 async function run(fn:()=>Promise<void>){setBusy(true);setError('');try{await fn();}catch(e){fail(e);}finally{setBusy(false);}}
 async function revision(url:string,p:Mutation,scopeKey:string,mode:RevisionMode='draft'){if(!box.current||!ready)throw new Error('기기의 임시 보관함을 준비하고 있습니다.');return box.current.revision(url,p,scopeKey,mode);}
 async function saveForStudent(sid:string,kind:string,entityId:string,body:unknown,originDate=date,baseOverride?:string,mode:RevisionMode='event',requestId?:string){destinationApplied.current=true;const previous=dataRef.current.ledger.find(e=>e.entity_id===entityId);return revision('/api/classroom',{id:requestId||crypto.randomUUID(),kind,entityId,studentId:sid,date:originDate,baseId:baseOverride??previous?.id??'',dependsOn:prerequisiteDependencies(body,dataRef.current.ledger),data:body},'class:'+entityId,mode);}
 async function saveClass(kind:string,entityId:string,body:unknown,originDate=date,baseOverride?:string,mode:RevisionMode='event'){await saveForStudent(studentId,kind,entityId,body,originDate,baseOverride,mode);}
 async function entry(kind:string,body:unknown,id=sessionId,captureId='',baseOverride?:string){const previous=latest(dataRef.current.events.filter(e=>e.session_id===id),kind);const p:Mutation={action:'entry',id:crypto.randomUUID(),sessionId:id,date,kind,baseId:baseOverride??previous?.id??'',captureId,data:body};if(['transcript','recording_notice'].includes(kind)){await box.current!.enqueue(p.id,'/api/notebook',p,jobDependencies(p,'/api/notebook'));}else await revision('/api/notebook',p,'entry:'+id+':'+kind);}
 async function createSession(forStudent=studentId,forDate=date,forTitle=title,forPurpose=purpose){
  if(!ready||!box.current)throw new Error('기기의 임시 보관함을 준비하고 있습니다.');
  destinationApplied.current=true;
  const id=crypto.randomUUID(),p:Mutation={action:'create',id,studentId:forStudent,date:forDate,title:forTitle.trim()||'수업 대화',purpose:forPurpose,createdAt:new Date().toISOString()};
  await box.current.enqueue(id,'/api/notebook',p);
  if(selectedRef.current===forStudent&&day.current===forDate){setSessionId(id);setTitle('');}return id;
 }
 async function stopCapture(){
  const rec=recorder.current;if(!rec)return;
  const result=await rec.stop();if(!result.safe)throw new Error(result.message);
  ++generation.current;setStatus(s=>({...s,phase:'paused',recording:false,transcribing:false,message:''}));setPartial('');
 }
 async function pauseRecording(){
  if(recordingTransition.current)return;recordingTransition.current=true;setBusy(true);setError('');
  try{await stopCapture();}catch(e){fail(e);}finally{recordingTransition.current=false;setBusy(false);}
 }
 async function startRecording(intent?:RecordingIntent){
  if(recordingTransition.current||!box.current||!ready)return;
  destinationApplied.current=true;
  const capturedBox=box.current,recordingStudent=intent?.studentId||studentId,recordingDate=intent?.date||date;
  const chosen=dataRef.current.sessions.find(s=>s.id===(intent?.sessionId??sessionId)&&s.student_id===recordingStudent&&!s.ended_at),chosenTitle=intent?.title??title,chosenPurpose=intent?.purpose??purpose,oldChoice=dockChoice;
  const request:RecordingIntent={studentId:recordingStudent,date:recordingDate,sessionId:intent?.sessionId||chosen?.id||'',title:chosenTitle,purpose:chosenPurpose,newConversation:!(intent?.sessionId||chosen?.id)};
  if(dataRef.current.captureMode==='voice_memos'){
   if(recorder.current?.isRecording||recorder.current?.emergency){fail(new Error('이전 웹 녹음을 멈추고 기기 보관을 먼저 확인해 주세요.'));return;}
   setDockChoice(request);setNativeTarget({...request});return;
  }
  recordingTransition.current=true;setBusy(true);setError('');
  try{
   if(recorder.current){const result=await recorder.current.stop();if(!result.safe)throw new Error(result.message);}
   const oldTarget=captureTarget.current,token=++generation.current,captureId=crypto.randomUUID();let sid=request.sessionId,allocated=false;
   const rec=new ClassRecorder(captureId,{
    status:value=>{if(generation.current===token){setStatus(value);setHasEmergency(!!recorder.current?.emergency);}},
    partial:value=>{if(generation.current===token)setPartial(value);},
    entry:async(text,cap,kind)=>{const p:Mutation={action:'entry',id:crypto.randomUUID(),sessionId:sid,date:recordingDate,kind:kind||'transcript',captureId:cap,data:{text}};await capturedBox.enqueue(p.id,'/api/notebook',p,jobDependencies(p,'/api/notebook'));}
   },capturedBox);
   recorder.current=rec;setDockChoice(request);setTarget({sessionId:sid,studentId:recordingStudent,date:recordingDate,captureId});setPartial('');
   try{
    await rec.prepare();if(!sid)sid=await createSession(recordingStudent,recordingDate,chosenTitle,chosenPurpose);
    await capturedBox.beginCapture({id:captureId,sessionId:sid,studentId:recordingStudent,date:recordingDate});allocated=true;
    const next={sessionId:sid,studentId:recordingStudent,date:recordingDate,captureId};captureTarget.current=next;setTarget(next);setDockChoice({...request,sessionId:sid,newConversation:false});
    await rec.start(()=>dataRef.current.connected&&navigator.onLine?post<{token:string}>('/api/connection',{action:'token'}).then(x=>x.token).catch(()=>null):Promise.resolve(null));
   }catch(e){
    if(allocated)await rec.stop(true);else{await rec.cancelSetup().catch(()=>{});++generation.current;recorder.current=null;captureTarget.current=oldTarget;setTarget(oldTarget);setDockChoice(oldChoice);setStatus({...idleRecording,phase:oldTarget?'paused':'idle'});}
    throw e;
   }
  }catch(e){fail(e);}finally{recordingTransition.current=false;setBusy(false);}
 }
 function dockRequest():RecordingIntent{
  return recordingRequest(dockChoice,dataRef.current,captureTarget.current);
 }
 async function ensureNativeSession(request:NativeCaptureTarget){
  const existing=request.sessionId?dataRef.current.sessions.find(s=>s.id===request.sessionId&&s.student_id===request.studentId&&s.class_date===request.date&&!s.ended_at):null;
  if(request.sessionId&&!existing)throw new Error('원래 녹음 대화를 확인할 수 없습니다. 녹음 대상을 다시 선택해 주세요.');
  const id=existing?.id||await createSession(request.studentId,request.date,request.title,request.purpose);
  await box.current!.flush();return id;
 }
 const currentDock=recordingRequest(dockChoice,data,target);
 const nativeCaptureMode=data.captureMode==='voice_memos';
 async function selectDockStudent(id:string){
  if(recordingTransition.current)return;const current=dockRequest();if(id===current.studentId){setDockPicker(false);return;}
  const open=dataRef.current.sessions.filter(s=>s.student_id===id&&s.class_date===date&&!s.ended_at&&!isTest(s)).at(-1),request={studentId:id,date,sessionId:open?.id||'',title:'',purpose:'lesson'};
  setDockPicker(false);if(active)await startRecording(request);else setDockChoice(request);
 }
 async function finishConversation(request:RecordingIntent){
  if(!request.sessionId||recordingTransition.current)return;
  const current=dockRequest();if(current.studentId!==request.studentId||current.sessionId!==request.sessionId||current.date!==request.date){setDockEnding(null);fail(new Error('녹음 대상이 바뀌었습니다. 마칠 대화를 다시 확인해 주세요.'));return;}
  const currentTarget=captureTarget.current,matches=currentTarget?.sessionId===request.sessionId;
  recordingTransition.current=true;setBusy(true);setError('');
  try{
   if(active&&!matches)throw new Error('녹음 중인 학생을 먼저 확인해 주세요.');
   if(matches)await stopCapture();
   await box.current!.enqueue('session-end-'+request.sessionId,'/api/notebook',{action:'end',id:request.sessionId},[...(matches&&currentTarget?['end-'+currentTarget.captureId]:[]),request.sessionId]);
   if(matches){++generation.current;captureTarget.current=null;setTarget(null);recorder.current=null;setStatus(idleRecording);}
   setDockChoice({...request,sessionId:'',newConversation:true});setDockEnding(null);setMessage('대화를 마쳤습니다. 원음과 관찰은 보존합니다.');
  }catch(e){fail(e);}finally{recordingTransition.current=false;setBusy(false);}
 }

 function copy(value:string){void navigator.clipboard.writeText(value).then(()=>setMessage('복사했습니다. 학원 사이트 또는 Tracker에서 대상 학생을 확인하고 반영하세요.')).catch(()=>{download('SPT_옮길내용.txt',value);setMessage('복사 권한이 없어 텍스트 파일로 준비했습니다.');});}
 function exportScope(){const content=exportClass(date,scope,dataRef.current.ledger,dataRef.current.sessions,dataRef.current.events,dataRef.current.captures,students);download(`SPT_${date}_${scope==='all'?'전체':scope}_수업후정리.md`,content,'text/markdown;charset=utf-8');setMessage('정리 파일을 ChatGPT에 첨부하세요. 테스트는 제외하고 이전 관찰은 수정 이력으로 구분했습니다.');}
 async function compare(job:LocalItem){await refresh();const p=job.payload!;let current:Entry|ClassEvent|undefined;if(job.url==='/api/classroom'){const r=await fetch('/api/classroom?entity='+encodeURIComponent(p.entityId!));if(!r.ok)throw new Error('연결 후 최신 수정본을 비교해 주세요.');current=(await r.json() as {ledger:ClassEvent[]}).ledger.at(-1);}else{const r=await fetch('/api/notebook?date='+p.date);if(!r.ok)throw new Error('연결 후 최신 관찰을 비교해 주세요.');current=latest((await r.json() as NotebookData).events.filter((e:Entry)=>e.session_id===p.sessionId),p.kind!);}setCompareChecked(false);setConflict({job,server:current?JSON.parse(current.body):{},baseId:current?.id||''});}
 const reviewStudents=students.filter(s=>(scheduled(date,students).some(x=>x.id===s.id)||data.sessions.some(x=>x.student_id===s.id&&!isTest(x))||data.ledger.some(x=>x.student_id===s.id&&x.class_date===date))&&(scope==='all'||classPart(s.id,date,students)===scope));
 const scopedStudent=studentId;
 const statusText:Record<RecordStatus['phase'],string>={idle:'녹음 대기',preparing:'마이크 준비 중',recording:'녹음 중',paused:'잠깐 멈춤',stopping:'녹음 마치는 중',ended:'대화 녹음 마침',interrupted:'녹음 중단 · 확인 필요'};
 const fieldOrigin=useRef<DOMRect|null>(null),fieldAnimation=useRef<Animation|null>(null);
 useEffect(()=>{
  fieldAnimation.current?.cancel();const origin=fieldOrigin.current;fieldOrigin.current=null;
  if(!fieldFocus||!origin||window.matchMedia('(prefers-reduced-motion: reduce)').matches)return;
  const heading=document.getElementById('student-heading');if(!heading?.animate)return;
  const rect=heading.getBoundingClientRect();
  fieldAnimation.current=heading.animate([{transform:`translate(${origin.left-rect.left}px,${origin.top-rect.top}px)`,opacity:.65},{transform:'translate(0,0)',opacity:1}],{duration:360,easing:'cubic-bezier(.22,.8,.25,1)'});
  return()=>fieldAnimation.current?.cancel();
 },[fieldFocus,studentId]);
 const [surface,setSurface]=useState<'class'|'after'|'tracker'>('class');
 const visibleSurface=fieldFocus?(tab==='class'?'class':'after'):surface;
 function openStudent(id:string,view='class'){setSurface(view==='class'?'class':'after');setTab(view);if(view==='review')setScope(classPart(id,date,students)||'all');choose(id);}
 function openAudio(id:string){const existing=dataRef.current.sessions.filter(s=>s.student_id===id&&s.class_date===date&&!s.ended_at&&!isTest(s)).at(-1);setNativeTarget({studentId:id,date,sessionId:existing?.id||'',title:'',purpose:'lesson'});}
 function selectSurface(value:'class'|'after'|'tracker'){destinationApplied.current=true;setSurface(value);setFieldFocus(false);}
 function openTracker(id:string){setStudentId(id);selectSurface('tracker');requestAnimationFrame(()=>document.getElementById('class-roster')?.scrollIntoView({block:'start',behavior:'instant'}));}
 const webMcpSynthetic=typeof window!=='undefined'&&window.location.origin==='http://127.0.0.1:4183'&&(!!data.rehearsalId||data.rosterSource==='synthetic');
 function webMcpSnapshot(source:NotebookData,sid=studentId,dayValue=date,refreshedAt=syncedAt):LessonSnapshot{return {studentId:sid,date:dayValue,knownStudent:students.some(s=>s.id===sid),synthetic:webMcpSynthetic,ready,online,serverIssue,syncedAt:refreshedAt,data:source};}
 async function webMcpStudentDone(input:StudentDoneInput):Promise<ToolResult>{
  const result=await markCurrentActivityStudentDone(webMcpSnapshot(dataRef.current),input,async command=>{
   if(!box.current||!ready)throw new Error('outbox unavailable');
   const saved=await saveForStudent(command.studentId,'activity',command.entityId,command.next,command.date,command.expectedRevisionId,'event');
   await box.current.flush();
   const response=await fetch('/api/classroom',{cache:'no-store',signal:AbortSignal.timeout(12000)});if(!response.ok)throw new Error('readback unavailable');
   const observed=await response.json() as {ledger:ClassEvent[]},refreshedAt=new Date().toISOString();
   return {revisionId:String(saved.id),snapshot:webMcpSnapshot({...dataRef.current,ledger:observed.ledger,localItems:[...box.current.items],classroomLoaded:true},command.studentId,command.date,refreshedAt)};
  });
  if(result.ok)void refresh();return result;
 }
 return <div className={"notebook-shell a-shell "+(fieldFocus?"detail-focused":"class-overview")}><a className="skip-link" href={fieldFocus?"#student-work":"#class-roster"}>수업 기록으로 건너뛰기</a><header className="topbar"><div className="brand"><span className="a-eyebrow">SPT · CLASSROOM</span><h1>{fieldFocus?"학생 기록":surface==='class'?'수업 중':surface==='after'?'수업 후':'원본 Tracker'}</h1></div><div className="top-actions"><label className="date-control">수업일<input type="date" aria-label="수업일" value={date} onChange={e=>void changeDate(e.target.value)} disabled={active||!!rehearsalDate}/></label><span className="private"><ShieldCheck size={16}/>강사 전용</span><button aria-label="화면·전사 설정" className="icon-button" onClick={()=>setSettings(true)}><Settings2 size={21}/></button><a href={SHEET_URL} target="_blank" rel="noreferrer">Tracker <ArrowUpRight size={16}/></a></div></header>
 {data.rehearsalId?<aside className="synthetic-notice" role="note" aria-label="격리 리허설"><strong>격리 리허설 · 실제 수업 기록과 분리</strong><span>연습용 내용과 짧은 테스트 음성을 사용하세요. 원본 반영은 테스트 전용이며, 체험 평가 기록은 초기화 후에도 보존됩니다.</span></aside>:data.rosterSource==='synthetic'&&<aside className="synthetic-notice" role="note" aria-label="합성 E2E 테스트 환경"><strong>합성 E2E 테스트 · 실제 수업 기록 아님</strong><span>가상 명단으로 동작을 확인하는 화면입니다. 실제 학생의 수업 내용이나 원음을 입력하지 마세요.</span></aside>}
 {nativeTarget&&<NativeCapture key={nativeTarget.studentId+':'+nativeTarget.date} target={nativeTarget} name={students.find(s=>s.id===nativeTarget.studentId)?.name||nativeTarget.studentId} names={Object.fromEntries(students.map(s=>[s.id,s.name]))} ensureSession={ensureNativeSession} onPrepared={id=>setDockChoice({...nativeTarget,sessionId:id,newConversation:false})} onChanged={()=>void refresh(nativeTarget.date)} onClose={()=>setNativeTarget(null)}/>}<RecorderDock external={nativeCaptureMode} ownerKey={ownerKey} identityKey={dockChoice.studentId+':'+dockChoice.date+':'+currentDock.sessionId} name={students.find(s=>s.id===dockChoice.studentId)?.name||dockChoice.studentId||'녹음 대상 선택'} state={!dockChoice.studentId?'대상 미선택':nativeCaptureMode&&!active?'음성메모 · 녹음 대상':(active||target?.studentId===dockChoice.studentId?statusText[status.phase]:currentDock.sessionId?'잠깐 멈춤':'녹음 대기')+(dockChoice.date!==date?' · '+dockChoice.date:'')} recording={status.recording&&target?.studentId===dockChoice.studentId} disabled={!ready||busy} canEnd={!nativeCaptureMode&&!!currentDock.sessionId} alert={status.phase==='interrupted'?(students.find(s=>s.id===target?.studentId)?.name||'')+' · '+(status.message||'녹음 보관 상태를 확인해 주세요.'):''} onTap={()=>{if(!dockChoice.studentId){setDockPicker(true);return;}void (active?pauseRecording():startRecording(dockRequest()));}} onChoose={()=>setDockPicker(true)} onEnd={()=>setDockEnding(dockRequest())} onRecover={()=>void run(async()=>{if(!recorder.current)return;await recorder.current.retryStorage();++generation.current;setStatus(s=>({...s,phase:'paused',recording:false}));setError('');})}/>
 <Dialog open={dockPicker} onOpenChange={setDockPicker}><DialogContent className="connection-dialog"><DialogHeader><DialogTitle>녹음할 학생 · {date}</DialogTitle><DialogDescription>{active?(students.find(s=>s.id===target?.studentId)?.name||'현재 학생')+' 녹음은 선택 전까지 계속됩니다.':'학생을 고른 뒤 독을 탭하면 녹음합니다.'}</DialogDescription></DialogHeader><div className="dock-student-picker">{students.filter(s=>s.active!==false||s.id===dockChoice.studentId).map(s=><button key={s.id} disabled={busy||!ready} aria-pressed={s.id===dockChoice.studentId} onClick={()=>void selectDockStudent(s.id)}><strong>{s.name}</strong><span>{active&&target?.studentId===s.id?'녹음 중':data.sessions.some(c=>c.student_id===s.id&&c.class_date===date&&!c.ended_at&&!isTest(c))?'열린 대화 있음':'새 대화 준비'}{studentId===s.id?' · 현재 화면':''}</span></button>)}</div></DialogContent></Dialog>
 <Dialog open={!!dockEnding} onOpenChange={v=>{if(!busy&&!v)setDockEnding(null);}}><DialogContent className="connection-dialog"><DialogHeader><DialogTitle>{students.find(s=>s.id===dockEnding?.studentId)?.name} 대화를 마칠까요?</DialogTitle><DialogDescription>{dockEnding?.date} · 원음과 관찰은 보존합니다. 다음 녹음은 새 대화로 시작합니다.</DialogDescription></DialogHeader><div className="button-row"><button disabled={busy} onClick={()=>setDockEnding(null)}>계속 두기</button><button disabled={busy} onClick={()=>{if(dockEnding)void finishConversation(dockEnding);}}>대화 마침</button></div></DialogContent></Dialog>
 <WebMCPRead label={student.name} snapshot={webMcpSnapshot(data)} markCurrentActivityStudentDone={webMcpStudentDone}/>
 <main>
 <nav className="a-nav" aria-label="작업 영역">{([['class','수업 중'],['after','수업 후'],['tracker','Tracker']] as const).map(([value,label])=><button key={value} aria-pressed={visibleSurface===value} onClick={()=>selectSurface(value)}>{label}</button>)}</nav>
 <div className={'sync-strip '+(failures.length?'has-error':!online?'is-offline':'')} role="status"><CloudUpload size={18}/><span>{!ready?'기기 보관 준비 중':failures.length?`확인할 저장 ${failures.length}건`:pending.length?`기기 보관 · 전송 대기 ${pending.length}건`:items.some(x=>x.type==='noteDraft'&&objectValue(x.value).text)?'작성 중 메모는 기기 보관 · 카드 저장 전':serverIssue?'서버 재확인 필요 · 기기 기록 유지':syncedAt?'서버 확인됨':'서버 기록 확인 중'}{!online?' · 인터넷 연결 끊김':''}</span><button className="quiet" onClick={()=>setQueueOpen(true)}>저장 상태</button><button className="quiet" onClick={()=>setAll(!all)}>{all?'예정만':'전체 명단'}</button><button className="quiet sync-refresh" aria-label="저장 상태 다시 확인" disabled={busy} onClick={()=>void run(async()=>{await box.current?.flush();await refresh();})}><RefreshCw size={16}/></button></div>
 {error&&<div className="error" role="alert">{error}<button aria-label="오류 닫기" onClick={()=>setError('')}>×</button></div>}{message&&<div className="success" role="status">{message}<button aria-label="안내 닫기" onClick={()=>setMessage('')}>×</button></div>}{status.message&&<p className="notice">{status.message}</p>}{syncMessage&&<p className="hint">{syncMessage}</p>}{hasEmergency&&<button className="stop-button" onClick={()=>download('SPT_마지막_미보관_음성.wav',pcmWav(recorder.current!.emergency!),'audio/wav')}>마지막 미보관 음성 내려받기</button>}
 <div className="workspace"><aside className="roster a-overview" id="class-roster" tabIndex={-1} hidden={fieldFocus}>{surface==='tracker'?<><section className="a-tracker-intro"><span className="a-eyebrow">PARK TRACKER</span><h2>원본 기록과 연결</h2><p>검토·확정한 학생 기록만 원본에 반영합니다. 기기 보관, 서버 보관, 원본 반영은 서로 다른 상태입니다.</p><a href={SHEET_URL} target="_blank" rel="noreferrer">원본 Tracker 열기 <ArrowUpRight size={16}/></a></section><nav className="a-student-switch" aria-label="원본 대조 학생">{roster.map(s=><button key={s.id} aria-pressed={studentId===s.id} onClick={()=>setStudentId(s.id)}><strong>{s.name}</strong><small>{classroomView(s.id,date,data).confirmationLabel}</small></button>)}</nav><p className="a-target-line"><strong>{student.name}</strong> · {date} 원본 기록</p><SheetPanel key={date+studentId} date={date} studentId={studentId} roster={students} data={data} onConnected={()=>void refresh()}/><DatasetPanel key={date} date={date} pending={pending.length} online={online}/></>:<ClassroomBoard key={date} students={roster} date={date} ledger={data.ledger} data={data} selected={studentId} ready={ready} view={surface} box={deviceOutbox} save={saveForStudent} onOpen={openStudent} onAudio={openAudio} onTracker={openTracker} fail={fail}/>}<details className="roster-origin"><summary>명단 출처·수업 시간</summary><p>{data.rosterSource==='synthetic'?'합성 테스트 명단 · 실제 Sheet 조회 아님':data.rosterSource==='sheet'?'교사가 대조한 Sheet 프로필':data.rosterRevision?'보관된 명단 · 출처 재확인':SOURCE_DATE+' 최초 명단 · Sheet 대조 전'}</p>{roster.map(s=><p key={s.id}>{s.name} · {classPart(s.id,date,students)} {classTime(s.id,date,students)}</p>)}<p>명단 순서는 고정입니다. 실제 출석·보강은 Tracker에서 확인하세요.</p></details></aside>
 <section className="student-work" id="student-work" aria-label="학생 기록" hidden={!fieldFocus}><div className="context-toolbar"><button className="quiet field-return" onClick={()=>{setSurface(tab==='class'?'class':'after');setFieldFocus(false);requestAnimationFrame(()=>{const el=document.getElementById('class-roster');el?.scrollIntoView({block:'start',behavior:'instant'});el?.focus({preventScroll:true});});}}>전체 학생</button><QuickWork current={student} date={date} students={roster} ledger={data.ledger} evidence={data} ready={ready} save={async(...args)=>{await saveForStudent(...args);}}/></div><div className="student-title"><div><h2 id="student-heading" tabIndex={-1}>{student.name}</h2><span className="student-schedule">{classPart(studentId,date,students)} · {classTime(studentId,date,students)}</span></div><span>{studentId==='S003'&&date==='2026-09-09'&&<span className="status-tag">첫 수업</span>}</span></div><p className="book-line">{student.books.join(' · ')||'교재 미입력'}</p>{student.active===false&&<p className="notice">정규 예정에서 제외한 학생입니다. 기존 대화와 미전송 기록을 보존합니다.</p>}{sourceLesson(studentId,date).startsWith('보강')&&<p className="hint">9/7 결석 수업의 보강 · 미해결 일은 직접 이어서 배정하세요.</p>}
 {sourceReturn!==null&&<button className="source-return" onClick={()=>{setTab('review');const y=sourceReturn;setSourceReturn(null);requestAnimationFrame(()=>{window.scrollTo({top:y,behavior:'instant'});sourceReturnFocus.current?.focus({preventScroll:true});});}}>수업 후 검토로 복귀</button>}<Tabs value={tab} onValueChange={value=>{destinationApplied.current=true;setTab(value);}}><TabsList className="work-tabs"><TabsTrigger value="class"><ClipboardList size={17}/>활동</TabsTrigger><TabsTrigger value="record"><Mic size={17}/>관찰·대화</TabsTrigger><TabsTrigger value="review"><FileCheck size={17}/>수업 후</TabsTrigger></TabsList>
 <TabsContent value="class" forceMount={tabVisits.tabs.includes('class')?true:undefined} hidden={tab!=='class'}><Activities key={studentId+date} studentId={studentId} date={date} ledger={data.ledger} save={saveClass} fail={fail} catalog={catalogFromSnapshot(data.sheet?.snapshot)}/></TabsContent>
 <TabsContent value="record" forceMount={tabVisits.tabs.includes('record')?true:undefined} hidden={tab!=='record'}>
 <ConversationList data={data} studentId={studentId} date={date} name={student.name} selectedId={sessionId} tests={tests} serverSessionIds={base.sessions.map(s=>s.id)} state={!online?'offline':serverIssue?'error':!ready||!syncedAt?'loading':'ready'} onSelect={id=>{setSessionId(id);if(!id){setTitle('');setPurpose('lesson');}}} onTests={v=>{setTests(v);if(!v&&session&&isTest(session))setSessionId('');}} onRefresh={()=>void run(async()=>{await refresh();})}/>
 {(session?isTest(session):purpose==='test')&&<p className="notice">테스트 대화입니다. 실제 관찰 카드는 수업 대화로 전환하면 표시됩니다. 아래 테스트 대화의 관찰은 수업 정리에서 제외됩니다.</p>}{ready&&deviceOutbox&&!(session?isTest(session):purpose==='test')&&<ObservationCards key={'cards'+studentId+date} studentId={studentId} name={student.name} date={date} events={data.events.filter(e=>data.sessions.some(s=>s.id===e.session_id&&s.student_id===studentId&&!isTest(s)))} scenes={data.ledger.filter(e=>e.student_id===studentId&&e.kind==='activity'&&JSON.parse(e.body).workDate===date&&!JSON.parse(e.body).cancelled).map(e=>{const t=JSON.parse(e.body);return {id:e.entity_id+':'+t.workDate,activity:t.title,range:t.range};})} box={deviceOutbox} ensureSession={async()=>{const s=dataRef.current.sessions.find(s=>s.id===sessionId&&s.student_id===studentId&&!s.ended_at&&!isTest(s))||dataRef.current.sessions.filter(s=>s.student_id===studentId&&!s.ended_at&&!isTest(s)).at(-1);return s?.id||createSession(studentId,date,'','lesson');}} position={()=>status.recording&&target?.studentId===studentId&&data.sessions.some(s=>s.id===target.sessionId&&!isTest(s))?{sessionId:target.sessionId,captureId:target.captureId,seconds:status.seconds}:null} fail={fail}/>}
 {!session?<section className="panel"><h3>새 대화 준비</h3><input aria-label="대화 제목" value={title} onChange={e=>setTitle(e.target.value)} placeholder="대화 제목 · 비워도 됩니다" maxLength={150}/><Pick label="기록 목적" value={purpose} onChange={setPurpose} items={[["lesson","실제 수업 기록"],["test","기능 테스트 · 정리에서 제외"]]}/><div className="button-row"><button className="primary" disabled={!ready||busy} onClick={()=>void startRecording()}><Mic size={17}/>{nativeCaptureMode?'음성 메모로 녹음':'녹음 시작'}</button><button disabled={!ready||busy} onClick={()=>void run(async()=>{await createSession();})}>관찰만 기록</button></div></section>:<><section className="panel conversation-heading"><h3>{isTest(session)&&'[테스트] '}{session.title}</h3><p>{formatTime(session.created_at)} 시작 · {session.ended_at?'마친 대화':'열린 대화'} · {events.filter(e=>e.kind==='transcript').length}개 전사 구간</p>{!session.ended_at&&!active&&<button onClick={()=>void run(async()=>{await box.current!.enqueue('session-end-'+session.id,'/api/notebook',{action:'end',id:session.id},[session.id]);})}>이 대화 마치기</button>}{partial&&target?.sessionId===session.id&&<p className="partial">인식 중 · {partial}</p>}</section><ConversationCandidates sessionId={session.id} events={events}/><details className="panel"><summary>기존 대화 관찰과 수정 이력</summary><Observation key={session.id} session={session} events={events} save={(v,b)=>entry('observation',v,sessionId,'',b)} fail={fail}/></details><TranscriptPanel key={'source'+session.id} events={events} captures={caps} save={entry} fail={fail}/></>}
 </TabsContent>
 <TabsContent value="review" forceMount={tabVisits.tabs.includes('review')?true:undefined} hidden={tab!=='review'}><CloseoutPanel key={'close'+studentId+date} studentId={studentId} date={date} ledger={data.ledger} roster={students} data={data} save={saveClass} retainReview={(id,text)=>entry('review_draft',{text},id)} fail={fail} copy={copy} allowAnalysis={fieldFocus&&tab==='review'} onTracker={()=>openTracker(studentId)}/><section className="panel export-panel"><div><h3>정리 파일 범위</h3></div><Pick label="정리 파일 범위" value={scope} onChange={setScope} items={[["1부","1부 수업"],["2부","2부 수업"],["보강","보강 수업"],["all","하루 전체"]]}/><button className="primary" onClick={exportScope}><Download size={18}/>ChatGPT 정리 파일</button>{pending.length>0&&<p className="hint">현재 기기에 보관된 미전송 내용도 포함합니다. 다른 기기의 미전송 내용은 포함되지 않습니다.</p>}</section><div className="review-roster">{reviewStudents.map(s=>{const r=values(data.ledger.find(e=>e.entity_id===entity('report',s.id,date)),blankReport),current=r.confirmed&&r.basis===reviewBasis(s.id,date,data.ledger,data.sessions,data.events);return <button key={s.id} className={scopedStudent===s.id?'selected':''} onClick={()=>choose(s.id)}>{s.name}<span>{current?r.transferredAt?'전송 완료 직접 표시':'교사 검토함':r.confirmed?'근거 변경 · 재검토':'검토 전'}</span></button>})}</div>{scopedStudent?<ReviewPanel key={'review'+scopedStudent+date} studentId={scopedStudent} date={date} data={data} save={async(...args)=>{await saveForStudent(scopedStudent,...args);}} fail={fail} copy={copy} onSource={id=>{sourceReturnFocus.current=document.activeElement as HTMLElement;setSourceReturn(window.scrollY);const s=data.sessions.find(s=>s.id===id)!;setStudentId(s.student_id);setSessionId(id);setTab('record');}}/>:<p className="empty-small">이 범위에 예정되거나 기록된 학생이 없습니다.</p>}<button className="primary" onClick={()=>selectSurface('tracker')}>원본 Tracker 저장·대조로 이동</button></TabsContent>
 </Tabs></section></div></main>
 <Dialog open={settings} onOpenChange={v=>{setSettings(v);if(!v)setKey('');}}><DialogContent className="connection-dialog"><DialogHeader><DialogTitle>화면·전사 설정</DialogTitle><DialogDescription>{nativeCaptureMode?'원본 보관과 전사 요청은 별개입니다. 키 등록만으로 전사를 실행하지 않으며, 해당 실행에서 허용한 요청에 API 이용량이 사용됩니다.':'키를 등록하면 녹음 중 음성을 ElevenLabs로 전사합니다. 해당 계정의 API 이용량이 사용됩니다.'}</DialogDescription></DialogHeader><Tick checked={opaque} onChange={value=>{setOpaque(value);try{localStorage.setItem('spt-opaque',String(value));}catch{}}}>투명 효과 줄이기</Tick><h3>{nativeCaptureMode?'파일 전사':'실시간 전사'}</h3>{data.connectionSource==='hermes'?<div className="native-connection" role="status"><p>{data.connected?'Hermes에 등록된 ElevenLabs 키 사용':'Hermes의 ElevenLabs 키 등록 필요'}</p><p className="hint">키는 Hermes의 기본 프로필에서 관리합니다. 필요한 연결 설정은 Hermes에 요청하세요. SPT에 다시 입력하거나 복사하지 않습니다. 등록 표시는 전사 허용량이나 실제 성공을 뜻하지 않습니다.</p></div>:<><p>{data.connected?'ElevenLabs 키 등록됨':'키가 없어도 원음과 관찰을 보관할 수 있습니다.'}</p><label>ElevenLabs API 키<input type="password" value={key} onChange={e=>setKey(e.target.value)} autoComplete="off" maxLength={1024}/></label><div className="button-row"><button disabled={!key||busy||active} className="primary" onClick={()=>void run(async()=>{await post('/api/connection',{action:'save',key});setKey('');await refresh();setSettings(false);setMessage('전사 연결 키를 보관했습니다.');})}>연결 등록</button>{data.connected&&<button disabled={busy||active} onClick={()=>void run(async()=>{await post('/api/connection',{action:'remove'});await refresh();})}>연결 해제</button>}</div></>}<p className="hint">{nativeCaptureMode?'음성 메모에서 녹음하고, 멈춘 후 원본을 SPT에 연결합니다. 녹음 중 다른 오디오를 재생하면 중단될 수 있습니다. 원본 업로드 중에는 Safari를 열어 두세요.':'웹 녹음은 화면 잠금·Safari 바깥 앱 전환 중 지속을 보장하지 않습니다.'}</p></DialogContent></Dialog>
 <Dialog open={queueOpen} onOpenChange={setQueueOpen}><DialogContent className="wide-dialog"><DialogHeader><DialogTitle>기기 보관과 전송</DialogTitle><DialogDescription>이미 수집한 음성과 입력을 기기에 보관하고, 연결되면 서버로 보냅니다. Safari의 사이트 데이터를 지우면 미전송 기록도 지워집니다.</DialogDescription></DialogHeader><p>{pending.length?`전송 대기 ${pending.length}건`:'전송 대기 없음'} · {online?'인터넷 연결됨':'인터넷 연결 끊김'}</p><button className="primary" onClick={()=>void run(async()=>{await box.current?.flush();await refresh();})}>다시 전송</button>{failures.map(j=><article className="conflict-row" key={j.key}><strong>{j.payload?.kind==='observation'?'관찰':String(objectValue(j.payload?.data).title||'보관 기록')}</strong><p>{j.error}</p>{j.code===409&&j.payload?.baseId!==undefined&&<button onClick={()=>void run(()=>compare(j))}>최신 내용과 비교</button>}<button onClick={()=>download('SPT_확인필요_입력.txt',readable(j.payload?.data||j.payload||{}))}>이 입력 내려받기</button></article>)}{[...new Set(pending.filter(j=>j.audioSize).map(j=>new URL(j.url!,'https://local.invalid').searchParams.get('capture')))].map(id=><button key={id} onClick={()=>void run(async()=>{const parts=pending.filter(j=>j.audioSize&&j.url?.includes('capture='+id)).sort((a,b)=>Number(new URL(a.url!,'https://local.invalid').searchParams.get('seq'))-Number(new URL(b.url!,'https://local.invalid').searchParams.get('seq'))),bytes=new Uint8Array(parts.reduce((n,j)=>n+j.audioSize!,0));let off=0;for(const j of parts){const chunk=await box.current!.readAudio(j.key);bytes.set(chunk,off);off+=chunk.length;}download(`SPT_${id}_미전송부분.wav`,pcmWav(bytes),'audio/wav');})}>미전송 음성 부분 내려받기</button>)}{items.some(j=>j.type==='conflictArchive')&&<details><summary>따로 보관한 충돌 입력</summary>{items.filter(j=>j.type==='conflictArchive').map(j=><article key={j.key}><pre>{readable(j.payload?.data||{})}</pre><button onClick={()=>download('SPT_따로보관한입력.txt',readable(j.payload?.data||{}))}>이 입력 내려받기</button></article>)}</details>}<p className="hint">미전송 부분 파일에는 이미 서버에 저장된 구간이 포함되지 않습니다. 전체 원음은 대화의 원문·음성에서 확인하세요.</p></DialogContent></Dialog>
 <Dialog open={!!conflict} onOpenChange={v=>{if(!v)setConflict(null);}}><DialogContent className="wide-dialog"><DialogHeader><DialogTitle>두 수정본 비교</DialogTitle><DialogDescription>기존 수정 이력을 유지하며, 어떤 내용을 현재 수정본으로 사용할지 확인합니다.</DialogDescription></DialogHeader>{conflict&&<><div className="comparison"><section><h3>서버의 최신 내용</h3><pre>{readable(conflict.server)}</pre></section><section><h3>이 기기에서 작성한 내용</h3><pre>{readable(conflict.job.payload?.data||{})}</pre></section></div><button onClick={()=>void run(async()=>{await box.current!.archiveConflict(conflict.job.key);setConflict(null);})}>서버 내용 유지 · 이 입력은 따로 보관</button>{!(isCardKind(conflict.job.payload?.kind||'')&&conflict.server.deleted)&&<><Tick checked={compareChecked} onChange={setCompareChecked}>두 내용을 확인했고 이 기기 내용을 새 수정본으로 보관합니다.</Tick><button className="primary" disabled={!compareChecked} onClick={()=>void run(async()=>{await box.current!.rebase(conflict.job.key,conflict.baseId);setConflict(null);await box.current!.flush();await refresh();})}>이 기기 내용으로 새 수정본 저장</button></>}</>}</DialogContent></Dialog>
 </div>;
}
function readable(value:unknown){const labels:Record<string,string>={observed:'직접 관찰',studentSaid:'학생 발언',next:'다음 확인',title:'활동',state:'상태',range:'범위',note:'메모',progress:'실제 진도',homework:'다음 숙제',due:'기한',noHomework:'숙제 없음',confirmed:'교사 확정',summary:'확인한 내용',needs:'미확인·재확인',parent:'학부모 문안',draft:'AI 초안',attempted:'시도',marked:'채점',corrected:'오답 재확인',unresolved:'미해결',materials:'점검 자료',inspectedAt:'점검 시각',feedbackAt:'피드백 시각',workDate:'배정일',lane:'담당',relation:'선행 관계',overrideReason:'순서 변경 이유',timing:'활동 시간',text:'내용'};return Object.entries(objectValue(value)).filter(([k])=>!['basis','prerequisite'].includes(k)).map(([k,v])=>`${labels[k]||k}: ${typeof v==='boolean'?v?'예':'아니오':Array.isArray(v)?v.join(', '):k==='timing'&&v?`배정 ${objectValue(v).assignedAt||'미기록'} / 종료 ${objectValue(v).stoppedAt||'–'} / 방문 ${objectValue(v).visitedAt||'–'} / 다시 보기 ${objectValue(v).revisitAt||'–'}`:v}`).join('\n\n');}
function TranscriptPanel({events,captures,save,fail}:{events:Entry[];captures:NotebookData['captures'];save:(kind:string,v:unknown)=>Promise<void>;fail:(e:unknown)=>void}){let initial={text:'',reason:''};try{initial=JSON.parse(parse(latest(events,'transcript_draft')).text||'{}')}catch{}const [draft,setDraft]=useState({...{text:'',reason:''},...initial});function change(p:Partial<typeof draft>){const next={...draft,...p};setDraft(next);void save('transcript_draft',{text:JSON.stringify(next)}).catch(fail);}return <details className="panel source-details" open={captures.length>0}><summary><Headphones size={18}/>원문·음성·정정 이력</summary><p className="hint">학생·화자·수학 용어는 교사 확인이 필요합니다. 전사 누락은 원음에서 확인하세요.</p>{captures.map((c,i)=><div className="audio-row" key={c.id}><span>{c.audio_source==='file_import'?'가져온 원음':'녹음'} {i+1} · {(c.samples/16000).toFixed(1)}초 서버 보관 · {c.state==='interrupted'?'중단 기록':c.state==='ended'?'녹음 마침':'녹음/보관 확인 중'}</span>{c.audio_source==='file_import'&&<audio controls preload="none" aria-label={'가져온 원음 '+(i+1)} src={'/api/audio?capture='+c.id+'&play=1'}/>}<a href={'/api/audio?capture='+c.id} target="_blank" rel="noreferrer">원음 내려받기</a></div>)}{events.filter(e=>['transcript','recording_notice','transcript_edit','review','ai_draft'].includes(e.kind)).map(e=><article className="transcript" key={e.id}><b>{formatTime(e.created_at)} · {{transcript:'전사 원문',recording_notice:'녹음 상태',transcript_edit:'추가·정정',review:'이전 대화별 교사 검토',ai_draft:'이전 대화별 AI 초안'}[e.kind]}</b><p>{parse(e).text||parse(e).summary}</p>{parse(e).reason&&<small>정정 이유 · {parse(e).reason}</small>}</article>)}<label className="field">전사문 추가·정정<textarea value={draft.text} onChange={e=>change({text:e.target.value})} maxLength={100000}/></label><label className="field">추가 출처·정정 이유<input value={draft.reason} onChange={e=>change({reason:e.target.value})} maxLength={1000}/></label><button disabled={!draft.text.trim()||!draft.reason.trim()} onClick={()=>void save('transcript_edit',draft).then(()=>change({text:'',reason:''})).catch(fail)}>원문을 유지하고 정정 보관</button></details>;}
