'use client';
import {useEffect,useLayoutEffect,useRef,useState,useSyncExternalStore,type PointerEvent,type KeyboardEvent} from 'react';
import {Mic,Pause,Play,AlertCircle,ChevronLeft,ChevronRight,MoreHorizontal} from 'lucide-react';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {clampDock,finishDockGesture,moveDockGesture,holdDelay,type DockGesture} from '@/lib/dock-gesture';
type Position={x:number;y:number;side:'left'|'right'};
const defaultPosition:Position={x:.5,y:1,side:'right'};
function subscribeDockStorage(notify:()=>void){window.addEventListener('storage',notify);return()=>window.removeEventListener('storage',notify);}
function dockStorage(owner:string){try{const raw=localStorage.getItem('spt-free-dock:'+owner);if(raw)return raw;const old=JSON.parse(localStorage.getItem('spt-dock-position:'+owner)||'null');return old?JSON.stringify({x:old.side==='left'?0:1,y:clampDock(old.ratio),side:old.side==='left'?'left':'right'}):'';}catch{return '';}}
function storedPosition(raw:string):Position{try{const p=JSON.parse(raw);if(Number.isFinite(p.x)&&Number.isFinite(p.y))return {x:clampDock(p.x),y:clampDock(p.y),side:p.side==='left'?'left':'right'};}catch{}return defaultPosition;}
type Gesture=DockGesture&{base:Position;grabX:number;grabY:number;identity:string;timer:ReturnType<typeof setTimeout>};
type Props={external?:boolean;ownerKey:string;identityKey:string;name:string;state:string;recording:boolean;disabled:boolean;canEnd:boolean;alert:string;onTap:()=>void;onChoose:()=>void;onEnd:()=>void;onRecover:()=>void};
export function RecorderDock(p:Props){
 const stored=useSyncExternalStore(subscribeDockStorage,()=>dockStorage(p.ownerKey),()=>''),[storedSource,setStoredSource]=useState(stored);
 const [position,setPosition]=useState<Position>(()=>storedPosition(stored)),[hidden,setHidden]=useState(false),[held,setHeld]=useState(false),[help,setHelp]=useState(false),[view,setView]=useState({x:0,y:0,w:360,h:700}),[size,setSize]=useState({w:160,h:60}),[edgeSize,setEdgeSize]=useState({w:72,h:48});
 if(storedSource!==stored){setStoredSource(stored);setPosition(storedPosition(stored));}
 const panel=useRef<HTMLDivElement|null>(null),edge=useRef<HTMLButtonElement|null>(null),safeArea=useRef<HTMLSpanElement|null>(null),positionRef=useRef(position),latest=useRef(p),gesture=useRef<Gesture|null>(null),suppress=useRef(false);
 useLayoutEffect(()=>{latest.current=p;positionRef.current=position;},[p,position]);
 function put(next:Position,save=false){positionRef.current=next;setPosition(next);if(save)try{localStorage.setItem('spt-free-dock:'+p.ownerKey,JSON.stringify(next));}catch{}}
 function cancel(){const g=gesture.current;if(!g)return;clearTimeout(g.timer);gesture.current=null;suppress.current=true;setHeld(false);put(g.base);}

 useEffect(()=>{const resize=()=>{const v=window.visualViewport,css=safeArea.current?getComputedStyle(safeArea.current):null,px=(key:string)=>parseFloat(css?.getPropertyValue(key)||'0')||0;setView({x:(v?.offsetLeft||0)+px('padding-left'),y:(v?.offsetTop||0)+px('padding-top'),w:(v?.width||window.innerWidth)-px('padding-left')-px('padding-right'),h:(v?.height||window.innerHeight)-px('padding-top')-px('padding-bottom')});};resize();window.addEventListener('resize',resize);window.visualViewport?.addEventListener('resize',resize);window.visualViewport?.addEventListener('scroll',resize);return()=>{cancel();window.removeEventListener('resize',resize);window.visualViewport?.removeEventListener('resize',resize);window.visualViewport?.removeEventListener('scroll',resize);};},[]);
 useEffect(()=>{const element=hidden?edge.current:panel.current,measure=()=>{if(element)(hidden?setEdgeSize:setSize)({w:element.offsetWidth,h:element.offsetHeight});};measure();const ro=new ResizeObserver(measure);if(element)ro.observe(element);return()=>ro.disconnect();},[hidden,p.name]);
 useEffect(()=>{cancel();},[p.identityKey,p.disabled]);
 useEffect(()=>{const focus=(event:FocusEvent)=>{if(event.target instanceof HTMLElement&&event.target.matches('input,textarea,select')){cancel();setHidden(true);}};document.addEventListener('focusin',focus);return()=>document.removeEventListener('focusin',focus);},[]);
 function stow(side:'left'|'right'){put({...positionRef.current,x:side==='left'?0:1,side},true);setHidden(true);requestAnimationFrame(()=>edge.current?.focus());}
 function restore(){setHidden(false);requestAnimationFrame(()=>panel.current?.querySelector<HTMLButtonElement>('button')?.focus());}
 function handlers(isEdge=false){return {
  onContextMenu:(e:{preventDefault:()=>void})=>e.preventDefault(),
  onPointerDown:(e:PointerEvent<HTMLElement>)=>{if(e.button!==0||!e.isPrimary||gesture.current)return;suppress.current=false;const rect=e.currentTarget.getBoundingClientRect(),g={id:e.pointerId,x:e.clientX,y:e.clientY,part:isEdge?'edge':(e.target as HTMLElement).closest('[data-dock-part]')?.getAttribute('data-dock-part')==='mic'?'mic':'name',held:false,moved:false,early:false,samples:[{x:e.clientX,y:e.clientY,t:performance.now()}],base:{...positionRef.current},grabX:e.clientX-rect.left,grabY:e.clientY-rect.top,identity:p.identityKey,timer:0 as unknown as ReturnType<typeof setTimeout>} as Gesture;g.timer=setTimeout(()=>{if(gesture.current!==g||g.early)return;g.held=true;setHeld(true);},holdDelay);gesture.current=g;e.currentTarget.setPointerCapture(e.pointerId);},
  onPointerMove:(e:PointerEvent<HTMLElement>)=>{const g=gesture.current;if(!g||g.id!==e.pointerId)return;moveDockGesture(g,e.clientX,e.clientY,performance.now());if(g.early)clearTimeout(g.timer);if(!g.held||!g.moved)return;const pad=isEdge?0:8,box=isEdge?edgeSize:size,x=clampDock((e.clientX-g.grabX-view.x-pad)/Math.max(1,view.w-box.w-pad*2)),y=clampDock((e.clientY-g.grabY-view.y-8)/Math.max(1,view.h-box.h-16));put({x,y,side:e.clientX-view.x<view.w/2?'left':'right'});},
  onPointerUp:(e:PointerEvent<HTMLElement>)=>{const g=gesture.current;if(!g||g.id!==e.pointerId)return;gesture.current=null;clearTimeout(g.timer);setHeld(false);const action=finishDockGesture(g,e.clientX,e.clientY,performance.now());suppress.current=action!=='tap';if(g.identity!==latest.current.identityKey){suppress.current=true;put(g.base);return;}if(action==='stow-left'||action==='stow-right')stow(action==='stow-left'?'left':'right');else if(action==='drag')put(positionRef.current,true);else if(!latest.current.disabled&&action==='choose')latest.current.onChoose();else if(!latest.current.disabled&&latest.current.canEnd&&action==='end')latest.current.onEnd();},
  onPointerCancel:cancel,onLostPointerCapture:(e:PointerEvent<HTMLElement>)=>{if(e.target===e.currentTarget&&gesture.current)cancel();},
  onClick:(e:{detail:number})=>{if(suppress.current&&e.detail!==0){suppress.current=false;return;}if(isEdge)restore();else if(!latest.current.disabled)latest.current.onTap();},
 };}
 function keyboard(e:KeyboardEvent<HTMLElement>,part:'name'|'mic'|'edge'){
  if(e.key==='Escape'){e.preventDefault();stow(positionRef.current.x<.5?'left':'right');return;}
  if(e.altKey&&['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.key)){e.preventDefault();const q={...positionRef.current};if(e.key==='ArrowLeft'){q.x=clampDock(q.x-.1);q.side='left';}if(e.key==='ArrowRight'){q.x=clampDock(q.x+.1);q.side='right';}if(e.key==='ArrowUp')q.y=clampDock(q.y-.1);if(e.key==='ArrowDown')q.y=clampDock(q.y+.1);put(q,true);return;}
  if(e.key==='ArrowDown'&&!p.disabled&&part==='name'){e.preventDefault();p.onChoose();}if(e.key==='Enter'&&e.shiftKey&&part==='mic'&&p.canEnd&&!p.disabled){e.preventDefault();p.onEnd();}
 }
 const icon=p.alert?<AlertCircle size={22}/>:p.recording?<Mic size={22}/>:p.canEnd?<Pause size={22}/>:<Play size={22}/>;
 const x=view.x+8+Math.max(0,view.w-size.w-16)*position.x,y=view.y+8+Math.max(0,view.h-size.h-16)*position.y;
 return <><span ref={safeArea} className="recorder-safe-area" aria-hidden="true"/><div className="recording-status-line"><span>{p.name} · {p.state}</span><button className="quiet" aria-label="녹음 독 조작 안내" onClick={()=>setHelp(true)}>?</button></div>
 {p.alert&&<div className="recorder-alert" role="alert">{p.alert}<button disabled={p.disabled} onClick={p.onRecover}>기기 보관 다시 시도</button></div>}
 <div ref={panel} className={'touch-recorder '+(held?'held ':'')+(p.recording?'recording':'')} hidden={hidden} style={{left:x,top:y,maxWidth:Math.max(100,view.w-16)}} role="group" aria-label={p.name+' 녹음 독 · '+p.state} onContextMenu={e=>handlers().onContextMenu(e)} onPointerDown={e=>handlers().onPointerDown(e)} onPointerMove={e=>handlers().onPointerMove(e)} onPointerUp={e=>handlers().onPointerUp(e)} onPointerCancel={()=>handlers().onPointerCancel()} onLostPointerCapture={e=>handlers().onLostPointerCapture(e)} onClick={e=>handlers().onClick(e)}>
 <button type="button" data-dock-part="name" aria-disabled={p.disabled} aria-label={p.name+' '+p.state+(p.external?'. 탭하여 음성 메모 녹음과 파일 연결.':'. 탭하여 멈춤 또는 재개.')+' 길게 누르고 놓아 학생 선택.'} onKeyDown={e=>keyboard(e,'name')}><span>{p.name}</span><small>{p.state}</small></button><button type="button" data-dock-part="mic" aria-disabled={p.disabled} aria-label={p.name+' '+p.state+(p.external?'. 음성 메모 녹음과 파일 연결 열기.':'. 길게 누르고 놓아 대화 종료 확인.')} onKeyDown={e=>keyboard(e,'mic')}>{icon}</button><button type="button" data-dock-part="menu" aria-label="녹음 독 메뉴" onPointerDown={e=>e.stopPropagation()} onClick={e=>{e.stopPropagation();setHelp(true);}}><MoreHorizontal size={20}/></button>
 </div>
 {hidden&&<button ref={edge} className={'touch-recorder-edge '+position.side+' '+(position.x>0&&position.x<1?'floating ':'')+(held?'held ':'')+(p.recording?'recording':'')} style={{top:view.y+8+Math.max(0,view.h-edgeSize.h-16)*position.y,left:view.x+Math.max(0,view.w-edgeSize.w)*position.x,maxWidth:Math.max(1,view.w)}} aria-label={p.name+' '+p.state+'. 탭하여 독 복귀. 길게 누른 채 자유롭게 이동.'} onContextMenu={e=>handlers(true).onContextMenu(e)} onPointerDown={e=>handlers(true).onPointerDown(e)} onPointerMove={e=>handlers(true).onPointerMove(e)} onPointerUp={e=>handlers(true).onPointerUp(e)} onPointerCancel={()=>handlers(true).onPointerCancel()} onLostPointerCapture={e=>handlers(true).onLostPointerCapture(e)} onClick={e=>handlers(true).onClick(e)} onKeyDown={e=>keyboard(e,'edge')}>{p.alert?<AlertCircle size={18}/>:position.side==='left'?<ChevronRight size={18}/>:<ChevronLeft size={18}/>}<span>{p.name}</span></button>}
 <Dialog open={help} onOpenChange={setHelp}><DialogContent className="connection-dialog"><DialogHeader><DialogTitle>녹음 독 조작</DialogTitle><DialogDescription>화면 학생과 녹음 학생은 따로 유지합니다.</DialogDescription></DialogHeader><p>{p.external?'탭: 표시된 학생의 음성 메모 녹음·파일 연결':'탭: 표시된 학생 멈춤·재개'}<br/>이름을 길게 누르고 놓기: 학생 선택<br/>{p.external?'녹음은 음성 메모 앱에서 멈춘 뒤 원본을 가져옵니다.':'마이크를 길게 누르고 놓기: 종료 확인'}<br/>길게 누른 채 이동: 독 이동<br/>좌우 밀기·빠르게 던지기: 옆으로 숨김<br/>손잡이 탭: 복귀</p><div className="button-row"><button disabled={p.disabled} onClick={()=>{setHelp(false);p.onChoose();}}>녹음 학생 선택</button><button disabled={p.disabled||!p.canEnd} onClick={()=>{setHelp(false);p.onEnd();}}>대화 마침</button><button onClick={()=>{setHelp(false);stow('left');}}>왼쪽에 숨김</button><button onClick={()=>{setHelp(false);stow('right');}}>오른쪽에 숨김</button></div><fieldset><legend>독 위치</legend><div className="button-row">{([['left','왼쪽'],['right','오른쪽'],['up','위로'],['down','아래로']] as const).map(([dir,label])=><button key={dir} onClick={()=>{const q={...positionRef.current};if(dir==='left'){q.x=0;q.side='left';}if(dir==='right'){q.x=1;q.side='right';}if(dir==='up')q.y=clampDock(q.y-.15);if(dir==='down')q.y=clampDock(q.y+.15);put(q,true);}}>{label}</button>)}</div></fieldset><p className="hint">키보드: 이름에서 ↓ 학생 선택, 마이크에서 Shift+Enter 종료 확인, Alt+방향키 이동, Escape 숨김.</p></DialogContent></Dialog>
 </>;
}
