'use client';
import {useEffect,useState} from 'react';
import type {Student} from '@/lib/notebook';
import type {SheetMapping,SheetSnapshot,SheetReceipt,SourceCell} from '@/lib/sheet-bridge';
import type {ClassEvent,Closeout} from '@/lib/classroom';
import type {NotebookData} from '@/lib/projection';
import {classroomView,reflectionLabels,retentionLabels} from '@/lib/classroom-view';
import {RecordProgress} from './record-progress';
type SheetPanelState={configured:boolean;connected:boolean;rehearsalId?:string;rosterRevision:string;mappings:SheetMapping[];lastSyncAt?:string;lastError?:string;snapshot?:SheetSnapshot;hash?:string;observedAt?:string;closeouts:ClassEvent[];receipts:SheetReceipt[];baselines:{student_id:string;remote_revision:string}[]};

const fieldNames:Record<string,string>={id:'학생 ID',status:'재원 상태',name:'이름',school:'학교',grade:'학년',className:'반',part:'부',days:'수업 요일',time:'수업 시간',firstDate:'최초 수업일',book1:'교재 1',book2:'교재 2',targetDate:'목표일',stage:'단계',nextAction:'다음 확인',note:'메모',teacher:'강사',lcad:'LCAD',previousAdvanceBook:'이전 선행 교재',previousAdvancePeriod:'이전 선행 기간',previousAdvanceEvaluationDate:'이전 선행 평가일',previousAdvanceScore:'이전 선행 점수',previousAdvancedBook:'이전 심화 교재',previousAdvancedPeriod:'이전 심화 기간',previousAdvancedEvaluationDate:'이전 심화 평가일',previousAdvancedScore:'이전 심화 점수',currentAdvanceBook:'현재 선행 교재',currentAdvanceStart:'현재 선행 시작일',currentAdvanceEnd:'현재 선행 종료일',currentAdvancedBook:'현재 심화 교재',currentAdvancedStart:'현재 심화 시작일',currentAdvancedEnd:'현재 심화 종료일'};
function SourceFields({title,cells}:{title:string;cells:SourceCell[]}){return <details><summary>{title}</summary><div className="source-table"><table><thead><tr><th>필드·원본 셀</th><th>현재 원문</th></tr></thead><tbody>{cells.map(c=><tr key={c.a1}><th>{fieldNames[c.field]||c.field.replace('column_','원본 열 ')}<small>{c.a1}</small></th><td>{c.display||'빈 값 · 미입력'}{c.formula&&<details><summary>원본 수식</summary><code>{c.formula}</code></details>}</td></tr>)}</tbody></table></div></details>;}
function CloseoutText({data}:{data:Partial<Closeout>|null|undefined}){return <dl className="facts"><dt>진도</dt><dd>{data?.progress||'미입력'}</dd><dt>숙제</dt><dd>{data?.noHomework?'없음':data?.homework||'미입력'}{!data?.noHomework&&data?.due&&' · '+data.due}</dd><dt>다음 확인</dt><dd>{data?.next||'미입력'}</dd></dl>;}
export function SheetPanel({date,studentId,roster,data,onConnected}:{date:string;studentId:string;roster:Student[];data?:NotebookData;onConnected:()=>void}){
 const [state,setState]=useState<SheetPanelState|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[selected,setSelected]=useState<Record<string,boolean>>({}),[compare,setCompare]=useState(false),[reviewed,setReviewed]=useState(false);
 async function refresh(){const r=await fetch('/api/sheet?date='+date,{cache:'no-store'});if(!r.ok)throw new Error('Sheet 연결 상태를 확인하지 못했습니다.');setState(await r.json() as SheetPanelState);}
 useEffect(()=>{void refresh().catch(e=>setError(e.message));const timer=setInterval(()=>void refresh().catch(()=>{}),15000);return()=>clearInterval(timer);},[date]);
 async function action(action:string,extra:Record<string,unknown>={}){setBusy(true);setError('');try{const r=await fetch('/api/sheet',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,date,...extra}),signal:AbortSignal.timeout(110000)});const reply=await r.json() as {error?:string;pendingSheet?:boolean};if(!r.ok)throw new Error(reply.error||'연결 결과를 확인해 주세요.');await refresh();if(action==='connect'){setCompare(false);setReviewed(false);onConnected();}if(action==='resolve'){setReviewed(false);if(reply.pendingSheet){const synced=await fetch('/api/sheet',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'sync',date}),signal:AbortSignal.timeout(110000)});if(!synced.ok){const issue=await synced.json() as {error?:string};throw new Error(issue.error||'앱 대조 결과를 보관했습니다. Sheet 연결을 다시 확인해 주세요.');}await refresh();}}}catch(e){setError(e instanceof Error?e.message:'연결 결과를 확인해 주세요.');await refresh().catch(()=>{});}finally{setBusy(false);}}
 const snapshot=state?.snapshot as SheetSnapshot|undefined;
 const [chosenRows,setChosenRows]=useState<Record<string,number>>({});
 const candidates=(snapshot?.profileSource.profiles||[]).map(profile=>{const student={id:profile.id,name:profile.name},matches=snapshot?.mainSource.rows.filter(r=>r.name===profile.name)||[],row=chosenRows[profile.id];return {student,profile:snapshot!.profileSource.profiles.filter(p=>p.id===profile.id).length===1?profile:null,matches,main:matches.find(r=>r.sourceRow===row)||(matches.length===1?matches[0]:null)};});
 const mappings:SheetMapping[]=candidates.filter(c=>selected[c.student.id]&&c.profile&&c.main).map(c=>({studentId:c.student.id,name:c.student.name,profileRow:c.profile!.sourceRow,mainRow:c.main!.sourceRow}));
 const local=state?.closeouts?.find(e=>e.student_id===studentId),localData=local?JSON.parse(local.body):null,remote=snapshot?.tracker.students.find(s=>s.studentId===studentId),latestRemote=state?.rehearsalId?remote?.latestTestReview:remote?.latestReview,receipts=state?.receipts?.filter(r=>r.student_id===studentId)||[],lastReceipt=receipts.at(-1),mapping=state?.mappings?.find(m=>m.studentId===studentId),baseline=state?.baselines?.find(r=>r.student_id===studentId),approved=localData?.resolution?.choice==='site'&&localData.resolution.comparedRemoteId===(latestRemote?.id||'')&&localData.resolution.comparedTrackerRevision===remote?.revision,conflict=!!mapping&&!!local&&!!remote&&!approved&&((latestRemote?.id||'')!==(lastReceipt?.remote_id||'')||remote.revision!==(baseline?.remote_revision??mapping?.trackerRevision??''));
 const reviewBasis=JSON.stringify([studentId,date,local?.id,remote?.revision]),[previousBasis,setPreviousBasis]=useState(reviewBasis);
 if(previousBasis!==reviewBasis){setPreviousBasis(reviewBasis);setReviewed(false);}
 const current=candidates.find(c=>c.student.id===studentId);
 const recordView=data?classroomView(studentId,date,{...data,sheet:state?{...state,date}:undefined}):null;
 const canResolveSite=recordView?.confirmation==='confirmed'&&recordView.retention==='server'&&recordView.record?.id===local?.id;
 const heading=!state?(error?'연결 확인 필요':'연결 상태 확인 중'):!recordView?'마감 근거 확인 전':['unknown','stale'].includes(recordView.confirmation)?recordView.confirmationLabel:['blocked','pending'].includes(recordView.retention)?retentionLabels[recordView.retention]:!state.configured?'연결 준비 전':!state.connected?'첫 대조 필요':!mapping?'이 학생 대조 전':conflict?'원본 수정 대조 필요':reflectionLabels[recordView.reflection];
 return <details className="panel sheet-panel"><summary>Sheet · {heading}{state?.lastError?' · 확인 필요':''}</summary>
  {recordView&&<RecordProgress view={recordView}/>}
  {state?.rehearsalId&&<p className="notice">리허설 · 원본에는 테스트 기록만 반영합니다. 자동 전송은 꺼져 있으며, 아래 버튼으로 명시적으로 반영합니다.</p>}
  <p>학생 기초정보를 원본 셀과 대조해 연결합니다. 이후 확정한 진도·숙제 마감은 Tracker에 반영하고, Sheet에서 바뀐 마감은 이 화면에서 비교할 수 있습니다.</p>
  <p className="hint">관찰·원음·전사·AI 초안은 앱에 보관합니다. 연결은 출석이나 교재별 확인 쪽수를 만들지 않습니다.</p>
  {!state?.configured&&<p className="notice">Sheet 연결을 준비하고 있습니다. 앱 기록은 계속 보관됩니다.</p>}
  {(error||state?.lastError)&&<p className="notice" role="alert">{error||state?.lastError}</p>}
  <div className="button-row"><button disabled={busy||!state?.configured} onClick={()=>{setCompare(true);setSelected({});void action('preview');}}>원본 학생·셀 대조</button>{state?.connected&&<button disabled={busy} onClick={()=>void action('sync')}>{state.rehearsalId?'테스트 마감 반영':'이 수업일의 확정 기록 동기화'}</button>}</div>
  {state?.connected&&<p className="hint">동기화는 선택 학생뿐 아니라 이 수업일의 확정 기록을 대상으로 합니다. 근거가 바뀐 기록은 다시 검토·확정해야 반영됩니다.</p>}
  {state?.lastSyncAt&&<p className="hint">마지막 확인 · {new Date(state.lastSyncAt).toLocaleString('ko-KR',{timeZone:'Asia/Seoul'})}</p>}
  {compare&&state&&snapshot&&<section><h4>가져오거나 갱신할 학생</h4><p className="hint">선택한 학생만 추가·갱신합니다. 기존 연결과 기록은 유지합니다. 퇴원 학생은 예정 명단에서 제외하고 이력을 보존합니다.</p><p className="hint">이름뿐 아니라 학생 ID와 원본 행을 확인하세요. 교재·기간·평가는 출처별 원문으로 보관하며 서로 다른 값을 임의로 합치지 않습니다.</p>
   {candidates.map(({student,profile,main,matches})=><article className="source-summary" key={student.id}><label className="checkbox-label"><input type="checkbox" disabled={!profile||!main||profile.name!==student.name} checked={!!selected[student.id]} onChange={e=>setSelected({...selected,[student.id]:e.target.checked})}/>{student.name} · {student.id} · {profile?.status!=='재원'?'예정 제외 · 이력으로 대조함':'원본 행 대조함'}</label>
    <p className="hint">앱 {student.name} ({student.id}) ↔ 학생표 {profile?.name||'연결 후보 없음'} {profile?'A'+profile.sourceRow:''} ↔ 메인 {main?.name||'연결 후보 없음'} {main?'C'+main.sourceRow:''}</p>
    {matches.length>1&&<label>같은 이름의 메인 행 선택<select value={chosenRows[student.id]||''} onChange={e=>{setChosenRows({...chosenRows,[student.id]:Number(e.target.value)});setSelected({...selected,[student.id]:false});}}><option value="">학년·교재 원문을 대조한 행 선택</option>{matches.map(m=><option value={m.sourceRow} key={m.sourceRow}>C{m.sourceRow} · {m.name} · {m.grade}</option>)}</select>{matches.map(m=><SourceFields key={m.sourceRow} title={'후보 C'+m.sourceRow+' 원문'} cells={m.cells}/>)}</label>}{profile&&<SourceFields title="학생 ID·운영 프로필 원문" cells={profile.cells}/>}{main&&<SourceFields title="LCAD·과거 평가·선행/심화 교재와 기간 원문" cells={main.cells}/>}</article>)}
   <button className="primary" disabled={busy||!mappings.length} onClick={()=>void action('connect',{confirmed:true,snapshotHash:state.hash,rosterRevision:state.rosterRevision,mappings})}>대조한 {mappings.length}명 연결</button></section>}
  {state?.connected&&snapshot&&<section><h4>{roster.find(s=>s.id===studentId)?.name} · {date} 마감 연결</h4><p className="hint">{mapping?.active===false?'재원 상태가 아니어서 새 마감 자동 전송은 멈췄습니다.':!mapping?'이 학생은 원본 행 대조 후 연결할 수 있습니다.':!local?'앱에 마감 기록이 없습니다.':recordView?.confirmation==='stale'?'근거가 바뀌어 다시 검토·확정해야 합니다. 원본의 이전 확정 기록은 보존됩니다.':recordView&&['pending','blocked'].includes(recordView.retention)?'이 기기의 최신 입력을 서버로 보내는 중이거나 확인이 필요합니다. 원본에는 이전 확정 내용이 남아 있습니다.':!localData.confirmed?'앱에서 재확정 전입니다. Sheet에는 마지막으로 확정한 내용이 남아 있습니다.':conflict?'Tracker의 다른 수정이 있어 자동 반영을 멈췄습니다.':recordView?.confirmation==='unknown'?'앱의 근거를 불러오는 중입니다. 이전 반영 이력을 현재 확정으로 간주하지 않습니다.':recordView?.reflection==='reflected'?'마지막 원본 조회에서 이 수정본의 반영을 확인했습니다.':'교사 확정 마감의 Sheet 반영을 기다리고 있습니다.'}</p>
   {conflict&&local&&remote&&<><div className="comparison"><section><h4>앱 마감</h4><CloseoutText data={localData}/></section><section><h4>현재 Tracker 마감</h4><CloseoutText data={latestRemote?.data}/></section></div><label className="checkbox-label"><input type="checkbox" checked={reviewed} onChange={e=>setReviewed(e.target.checked)}/>학생·수업일·두 마감 내용을 대조했습니다.</label><div className="button-row"><button disabled={busy||!reviewed||!canResolveSite} onClick={()=>void action('resolve',{confirmed:true,choice:'site',entryId:local.id,remoteId:latestRemote?.id||'',trackerRevision:remote!.revision,recordedAtClient:new Date().toISOString()})}>대조한 앱 마감으로 반영 요청</button><button disabled={busy||!reviewed||!latestRemote} onClick={()=>void action('resolve',{confirmed:true,choice:'sheet',entryId:local.id,remoteId:latestRemote?.id||'',trackerRevision:remote!.revision,recordedAtClient:new Date().toISOString()})}>대조한 Sheet 마감을 앱에 반영</button></div><p className="hint">이전 기록과 전송 이력은 보존됩니다. 마감이 바뀌면 기존 학부모 문안은 다시 검토해야 합니다.</p></>}
   {current?.profile&&<SourceFields title="이 학생의 현재 Sheet 기초정보" cells={current.profile.cells}/>} {current?.main&&<SourceFields title="이 학생의 교재·기간·평가 원문" cells={current.main.cells}/>}<p className="hint">가져온 시각 · {state.observedAt?new Date(state.observedAt).toLocaleString('ko-KR',{timeZone:'Asia/Seoul'}):'미확인'} · 실제 수정 시각과 구분합니다.</p>
  </section>}
 </details>;
}
