import {z} from 'zod';

const id=z.string().min(1).max(160),text=z.string().min(1).max(12000);
const scenario=z.object({id,category:z.enum(['workflow','safety','uiux','design']),title:text,expected:text}).strict();
const feedback=z.object({id,scenarioId:id,category:z.enum(['defect','friction','design','capability','note']),quote:text,sourceRef:text,evidenceRefs:z.array(text),authorRole:z.enum(['teacher','agent','automated']).optional(),observedAt:z.string().datetime({offset:true}).optional()}).strict();
const decision=z.object({id,disposition:z.enum(['accept','conditional_accept','repair','defer','stop']),reason:text,feedbackIds:z.array(id),nativeTaskIds:z.array(id),authorRole:z.enum(['teacher','agent']).optional()}).strict();
const review=z.object({
 schema:z.literal('product-experience-review/1'),id:z.string().uuid(),productId:z.string().regex(/^[a-z0-9][a-z0-9-]*$/),createdAt:z.string().datetime({offset:true}),
 status:z.enum(['preparing','ready','running','reviewed','accepted','conditional','rejected']),
 target:z.object({kind:z.enum(['release','design']),platform:z.enum(['web','ios','android','design']),label:text,buildId:text.optional(),artifactRef:text,baseReleaseRef:text.optional(),runtimeRef:text.optional()}).strict(),
 environment:z.object({origin:z.string().url().refine(v=>v.startsWith('https://')||v.startsWith('http://127.0.0.1:')),description:text,device:text,capabilities:z.array(text)}).strict(),
 scenarios:z.array(scenario).min(1),feedback:z.array(feedback),decisions:z.array(decision),
 reset:z.object({state:z.enum(['not_started','retired','verified']),evidenceRef:text.optional()}).strict(),nativeTaskId:id,
}).strict().superRefine((r,ctx)=>{
 const fail=(message:string)=>ctx.addIssue({code:z.ZodIssueCode.custom,message});
 for(const list of [r.scenarios,r.feedback,r.decisions])if(new Set(list.map(x=>x.id)).size!==list.length)fail('Duplicate review identity');
 if(r.target.kind==='release'&&!r.target.buildId)fail('A release review needs its exact build identity');
 for(const f of r.feedback)if(!r.scenarios.some(s=>s.id===f.scenarioId))fail('Feedback scenario is not in this review');
 for(const d of r.decisions)if(d.feedbackIds.some(i=>!r.feedback.some(f=>f.id===i)))fail('Decision refers to missing feedback');
 if(['accepted','conditional'].includes(r.status)&&(!r.feedback.some(f=>f.authorRole==='teacher')||!r.decisions.some(d=>d.authorRole==='teacher'&&['accept','conditional_accept'].includes(d.disposition))))fail('User acceptance needs direct teacher evidence and decision');
 if(r.reset.state!=='not_started'&&!r.reset.evidenceRef)fail('A reset needs its observed evidence');
});
export type ProductReview=z.infer<typeof review>;
export type ProductFeedback=z.infer<typeof feedback>;
export function validateReview(value:unknown):ProductReview{return review.parse(value);}
export function appendFeedback(value:unknown,input:unknown):ProductReview{const r=validateReview(value),f=feedback.parse(input);return validateReview({...r,feedback:[...r.feedback,f]});}
const escape=(value:unknown)=>String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
const status:Record<ProductReview['status'],string>={preparing:'준비 중',ready:'체험 준비됨 · 평가 전',running:'체험 중',reviewed:'의견 검토됨',accepted:'사용자 수용',conditional:'조건부 수용',rejected:'수정 필요'};
const category:Record<string,string>={workflow:'업무 흐름',safety:'정확성·안전',uiux:'UI/UX',design:'디자인',defect:'결함',friction:'사용 불편',capability:'미충족 기능',note:'관찰'};
/** A derived portable view. Records remain the source; native Tasks own work. */
export function renderReviews(values:unknown[]):string{
 const records=values.map(validateReview).sort((a,b)=>b.createdAt.localeCompare(a.createdAt));
 if(new Set(records.map(r=>r.id)).size!==records.length)throw Error('Duplicate run in review index');
 const groups=new Map<string,ProductReview[]>();for(const r of records){const key=r.productId+' / '+r.target.platform+' / '+(r.target.buildId||r.target.artifactRef);groups.set(key,[...(groups.get(key)||[]),r]);}
 const cards=[...groups].map(([key,runs])=>`<section class="release"><div class="eyebrow">${escape(key)}</div><h2>${escape(runs[0].target.label)}</h2>${runs.map(r=>`<article id="run-${r.id}"><header><strong>${escape(status[r.status])}</strong><span>${escape(r.createdAt)}</span></header><p>${escape(r.environment.description)}</p><p class="muted">${escape(r.environment.device)} · ${escape(r.environment.origin)}</p><div class="facts"><span>피드백 ${r.feedback.length}</span><span>결정 ${r.decisions.length}</span><span>초기화 ${escape(r.reset.state)}</span></div><details open><summary>체험·평가 범위</summary>${r.scenarios.map(s=>`<div class="scenario"><b>${escape(category[s.category])} · ${escape(s.title)}</b><p>${escape(s.expected)}</p></div>`).join('')}</details><details ${r.feedback.length?'open':''}><summary>피드백과 근거</summary>${r.feedback.length?r.feedback.map(f=>`<blockquote><span class="eyebrow">${escape(category[f.category])} · ${escape(f.scenarioId)}</span><p>${escape(f.quote)}</p><small>원문 ${escape(f.sourceRef)}</small>${f.evidenceRefs.map(e=>`<code>${escape(e)}</code>`).join('')}</blockquote>`).join(''):'<p class="muted">아직 이 회차의 사용자 체험 의견이 없습니다. 준비나 자동 테스트 통과를 사용자 수용으로 표시하지 않습니다.</p>'}</details><details ${r.decisions.length?'open':''}><summary>결정·후속 작업</summary>${r.decisions.length?r.decisions.map(d=>`<p><b>${escape(d.disposition)}</b> — ${escape(d.reason)}<br><small>${escape(d.nativeTaskIds.join(', '))}</small></p>`).join(''):'<p class="muted">판정 전</p>'}</details><details><summary>버전·실행 조건·초기화 근거</summary><code>Run ${escape(r.id)}</code><code>${escape(r.target.artifactRef)}</code>${r.target.baseReleaseRef?`<code>Base ${escape(r.target.baseReleaseRef)}</code>`:''}${r.target.runtimeRef?`<code>Runtime ${escape(r.target.runtimeRef)}</code>`:''}<p>${r.environment.capabilities.map(escape).join(' · ')}</p><code>${escape(r.reset.evidenceRef||'초기화 미실행')}</code></details><button data-hermes-send="SPT 제품 체험 ${r.id}의 현재 단계에 대한 피드백을 기록하자. 먼저 내 의견을 물어봐줘.">이 체험에 의견 남기기</button></article>`).join('')}</section>`).join('');
 return `<!doctype html><html lang="ko"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>제품 체험 · 버전별 리뷰</title><style>:root{color-scheme:light dark}body{margin:0;font-family:system-ui,sans-serif;background:var(--card,#f7f8fa);color:var(--foreground,#202a36)}main{max-width:1000px;padding:24px}h1{font-size:28px;margin:0 0 8px}h2{font-size:21px;margin:8px 0 16px}.intro,.muted,small{color:var(--muted-foreground,#687382)}.eyebrow{font-size:12px;overflow-wrap:anywhere;color:var(--muted-foreground,#687382)}.release{margin:28px 0}article{border:1px solid var(--border,#ccd3dd);border-radius:14px;padding:20px;margin:12px 0;background:var(--card,#fff)}header{display:flex;flex-wrap:wrap;gap:8px;justify-content:space-between}header strong{color:var(--accent,#3160a4)}header span{font-size:13px}.facts{display:flex;gap:12px;flex-wrap:wrap;font-size:13px;margin:14px 0}details{border-top:1px solid var(--border,#dce1e8);padding:12px 0}summary{cursor:pointer;font-weight:600}.scenario{padding:10px 0}.scenario p{margin:5px 0}p{line-height:1.65}blockquote{margin:12px 0;padding:12px;border-left:3px solid var(--accent,#3160a4);background:var(--card,#f7f9fc)}code{display:block;font-size:12px;overflow-wrap:anywhere;white-space:pre-wrap;margin:5px 0}button{font:inherit;padding:10px 14px;border:1px solid var(--border,#bbc7d8);border-radius:9px;background:var(--card,#eef3fa);color:inherit;cursor:pointer}@media(max-width:500px){main{padding:14px}article{padding:14px}h1{font-size:24px}}</style></head><body><main><div class="eyebrow">PRODUCT EXPERIENCE REVIEW</div><h1>버전별 체험과 평가</h1><p class="intro">업무 흐름 · 정확성 · UI/UX · 디자인. 테스트 상태는 초기화해도, 버전과 의견·근거·결정은 남습니다.</p><p>${records.length}개 체험 회차 · ${groups.size}개 대상 버전</p>${cards||'<p>기록된 체험이 없습니다.</p>'}<footer class="muted">이 화면은 기록에서 생성한 보기입니다. 실제 학생 자료와 원음은 격리된 비공개 저장소에 남으며, 이 목록은 native Task나 배포 권한을 대체하지 않습니다.</footer></main></body></html>`;
}
