import {owner,db,bucket,result,failure,ApiError,ownedCapture,sha} from '@/lib/server';
import {uuid} from '@/lib/notebook';
import {originalAudio} from '@/lib/audio-import';
import type {AudioImport} from '@/lib/audio-import-model';
export const dynamic='force-dynamic';
export async function POST(request:Request){try{const user=await owner(request);const url=new URL(request.url),id=url.searchParams.get('capture')||'',seq=Number(url.searchParams.get('seq'));if(!uuid(id)||!Number.isSafeInteger(seq)||seq<0||seq>180000)throw new ApiError('음성 구간을 확인해 주세요.');const c=await ownedCapture(id,user);if(c.state==='deleted')throw new ApiError('삭제된 녹음입니다.',409);if(await db().prepare('SELECT id FROM spt_audio_imports WHERE id=? AND owner=?').bind(id,user).first())throw new ApiError('가져온 원본에 다른 녹음 구간을 덧붙일 수 없습니다.',409);const bytes=await request.arrayBuffer();if(bytes.byteLength<2||bytes.byteLength>1048576||bytes.byteLength%2)throw new ApiError('음성 구간 크기가 올바르지 않습니다.',413);const hash=await sha(bytes),chunkId=id+'-'+seq;const old=await db().prepare('SELECT * FROM spt_audio_chunks WHERE id=?').bind(chunkId).first();if(old){if(old.owner!==user||old.hash!==hash)throw new ApiError('같은 음성 구간의 내용이 다릅니다.',409);return result({saved:true,id,seq});}const key='spt/'+user+'/'+id+'/'+String(seq).padStart(6,'0')+'.pcm';const stored=await bucket().put(key,bytes,{httpMetadata:{contentType:'application/octet-stream'},customMetadata:{sha256:hash},onlyIf:{etagDoesNotMatch:'*'}});if(!stored){const head=await bucket().head(key);if(head?.customMetadata?.sha256!==hash)throw new ApiError('같은 음성 구간의 내용이 다릅니다.',409);}await db().prepare('INSERT INTO spt_audio_chunks(id,owner,capture_id,seq,size,hash,object_key,created_at) VALUES(?,?,?,?,?,?,?,?) ON CONFLICT(id) DO NOTHING').bind(chunkId,user,id,seq,bytes.byteLength,hash,key,new Date().toISOString()).run();const check=await db().prepare('SELECT hash FROM spt_audio_chunks WHERE id=? AND owner=?').bind(chunkId,user).first();if(check?.hash!==hash)throw new ApiError('음성 보관 결과가 달라 확인이 필요합니다.',409);return result({saved:true,id,seq});}catch(e){return failure(e)}}
export async function GET(request:Request){try{const user=await owner();const id=new URL(request.url).searchParams.get('capture')||'';if(!uuid(id))throw new ApiError('녹음을 선택해 주세요.');await ownedCapture(id,user);const imported=await db().prepare('SELECT * FROM spt_audio_imports WHERE id=? AND owner=?').bind(id,user).first<AudioImport&{owner:string}>();if(imported)return await originalAudio(request,imported);const r=await db().prepare('SELECT seq,size,object_key FROM spt_audio_chunks WHERE capture_id=? AND owner=? ORDER BY seq').bind(id,user).all<{seq:number;size:number;object_key:string}>();const rows=r.results;if(!rows.length)throw new ApiError('보관된 음성이 없습니다.',404);if(rows.some((r,i)=>r.seq!==i))throw new ApiError('일부 음성 구간이 아직 전송되지 않았습니다. 녹음한 기기에서 다시 전송해 주세요.',409);const size=rows.reduce((s,r)=>s+r.size,0);const b=new ArrayBuffer(44),v=new DataView(b);const put=(o:number,s:string)=>{for(let i=0;i<s.length;i++)v.setUint8(o+i,s.charCodeAt(i))};put(0,'RIFF');v.setUint32(4,36+size,true);put(8,'WAVEfmt ');v.setUint32(16,16,true);v.setUint16(20,1,true);v.setUint16(22,1,true);v.setUint32(24,16000,true);v.setUint32(28,32000,true);v.setUint16(32,2,true);v.setUint16(34,16,true);put(36,'data');v.setUint32(40,size,true);
 const store=bucket();let index=-1,reader:ReadableStreamDefaultReader<Uint8Array>|null=null;const stream=new ReadableStream<Uint8Array>({async pull(controller){try{if(index===-1){controller.enqueue(new Uint8Array(b));index=0;return;}for(;;){if(reader){const part=await reader.read();if(!part.done){controller.enqueue(part.value);return;}reader=null;index++;}if(index>=rows.length){controller.close();return;}const obj=await store.get(rows[index].object_key);if(!obj)throw new Error('missing audio');reader=obj.body.getReader();}}catch(e){controller.error(e)}},cancel(){return reader?.cancel()}});return new Response(stream,{headers:{'Content-Type':'audio/wav','Cache-Control':'no-store','Content-Disposition':`attachment; filename="SPT-${id}.wav"`}});
 }catch(e){return failure(e)}}
