import {AUDIO_TRANSFER_PROTOCOL,AUDIO_TRANSFER_SHORTCUT} from '@/lib/audio-transfer-model';
import Link from 'next/link';
export default function ShortcutSetup(){return <main className="notebook-shell" style={{maxWidth:840,margin:'0 auto',padding:20}}>
 <header><p>SPT · ORIGINAL TRANSFER</p><h1>단축어 자동 전송 · 최초 설정</h1><p>기존 녹음은 그대로 두고, 끝난 파일을 기기에 보관한 다음 전송합니다. 이 안내는 설치 완료나 실제 iPhone 검증을 뜻하지 않습니다.</p></header>
 <section className="panel"><h2>먼저 준비</h2><ol><li>파일 앱의 <strong>나의 iPhone</strong> 아래에 <strong>SPT</strong> 폴더를 한 번 만드세요. iCloud Drive가 아닌 기기 안의 폴더입니다.</li><li>기존 ‘SPT 녹음’을 복제해 <strong>{AUDIO_TRANSFER_SHORTCUT}</strong>으로 이름을 정하세요. 원래 단축어는 남깁니다.</li><li>복사본의 기존 녹음 동작과 그 반환 파일을 사용합니다. 복사본에 ‘저장 위치 묻기’나 파일 선택 동작이 있다면 아래 고정 폴더 저장으로 대체합니다. 녹음 설정 자체는 바꾸지 않습니다.</li></ol></section>
 <section className="panel"><h2>1 · 녹음 전에 전송 대상을 받기</h2><p>다음 동작을 녹음 동작보다 앞에 놓으세요. 대괄호는 직접 입력할 글자가 아니라 선택할 변수입니다.</p><ol><li><strong>입력에서 사전 가져오기</strong>: 입력은 [단축어 입력]. 결과를 변수 <strong>SPT 요청</strong>으로 정합니다.</li><li><strong>사전 값 가져오기</strong>: [SPT 요청]에서 <code>importId</code> → 변수 <strong>녹음 ID</strong>, <code>token</code> → 변수 <strong>전송 권한</strong>.</li><li><strong>텍스트 일치</strong>: [녹음 ID]를 아래 정규식과 대조합니다. 일치가 없으면 ‘SPT에서 새 녹음 연결을 준비하세요’ 알림 후 <strong>이 단축어 중단</strong>.</li></ol><pre style={{overflowWrap:'anywhere',whiteSpace:'pre-wrap'}}>{'^[0-9a-fA-F]{8}(-[0-9a-fA-F]{4}){3}-[0-9a-fA-F]{12}$'}</pre><ol start={4}><li><strong>URL 콘텐츠 가져오기</strong>: 아래 고정 주소, 메서드 <code>GET</code>. 헤더 <code>X-SPT-Transfer</code>에 [전송 권한]을 넣습니다. 결과를 <strong>사전</strong>으로 읽고 변수 <strong>사전 확인</strong>에 보관하세요.</li></ol><pre style={{overflowWrap:'anywhere',whiteSpace:'pre-wrap'}}>https://spt.kcpalantir.tech/api/audio-transfer/status</pre><p>[사전 확인]의 <code>protocol</code>이 <code>{AUDIO_TRANSFER_PROTOCOL}</code>이고 <code>importId</code>가 [녹음 ID]와 같아야 합니다. 아니면 중단하세요. 오류가 나면 녹음을 시작하지 않습니다. 입력으로 들어온 임의의 다른 서버 주소는 사용하지 마세요.</p><p><code>stored</code>가 참이면 이미 서버 보관된 원본입니다. 다시 녹음하지 말고, [사전 확인]의 <code>returnURL</code>을 <strong>URL 열기</strong>로 연 뒤 <strong>이 단축어 중단</strong>으로 끝내세요. 아래 녹음 단계로 계속 내려가면 안 됩니다.</p></section>
 <section className="panel"><h2>2 · 기기에 먼저 자동 보관</h2><ol><li><strong>폴더 생성</strong>: 앞에서 고른 ‘나의 iPhone / SPT’ 안에 [녹음 ID] 이름의 폴더를 만듭니다. 그 결과 폴더를 변수 <strong>녹음 폴더</strong>로 정합니다.</li><li><strong>폴더 콘텐츠 가져오기</strong>: [녹음 폴더], 하위 폴더 포함은 끕니다. 결과의 <strong>개수</strong>를 확인합니다.</li><li>파일이 <strong>0개</strong>일 때만 기존 녹음 동작을 실행합니다. 녹음을 멈추면 반환된 파일을 <strong>파일 저장</strong>으로 [녹음 폴더]에 보관합니다. <strong>저장 위치 묻기 끄기 · 기존 파일 덮어쓰기 끄기</strong>. 저장한 파일을 변수 <strong>원본 파일</strong>로 정합니다.</li><li>파일이 <strong>1개</strong>이면 녹음하지 않습니다. <strong>목록에서 항목 가져오기 → 첫 번째 항목</strong>을 [원본 파일]로 정합니다. 실패 후 재시도할 때도 이 파일을 사용합니다.</li><li>파일이 여러 개라면 임의로 고르지 말고 알림 후 중단합니다. 폴더에는 해당 녹음 원본 하나만 보관하세요.</li></ol><p>원본 이름과 확장자는 유지합니다. 이름을 학생 이름으로 추측해 바꾸지 않습니다. 어떤 경우에도 자동 삭제 동작을 넣지 마세요.</p></section>
 <section className="panel"><h2>3 · 파일 자체를 전송</h2><ol><li>[원본 파일]의 <strong>이름 가져오기</strong>에서 확장자를 포함한 이름을 가져옵니다. 예: <code>녹음.m4a</code>. 확장자 제외 옵션이 있다면 끕니다.</li><li>그 이름에 <strong>URL 인코딩</strong>을 적용하고 변수 <strong>파일 이름</strong>으로 정합니다.</li><li><strong>URL 콘텐츠 가져오기</strong>: 아래 고정 주소, 메서드 <code>POST</code>, 요청 본문 <strong>파일</strong>에 [원본 파일]을 넣습니다. JSON·폼·파일 경로 문자열이 아닙니다.</li></ol><pre style={{overflowWrap:'anywhere',whiteSpace:'pre-wrap'}}>https://spt.kcpalantir.tech/api/audio-transfer/upload</pre><p>헤더는 아래 두 개입니다.</p><ul><li><code>X-SPT-Transfer</code> → [전송 권한]</li><li><code>X-SPT-Filename</code> → URL 인코딩한 [파일 이름]</li></ul><p>Cookie나 ElevenLabs API 키를 넣지 않습니다. Content-Length는 직접 작성하지 않습니다.</p></section>
 <section className="panel"><h2>4 · 확인하고 같은 녹음으로 돌아오기</h2><p>응답을 사전으로 읽습니다. <code>protocol</code>이 위 값과 같고, <code>importId</code>가 [녹음 ID]와 같고, <strong><code>stored</code>와 <code>inputConfirmed</code>가 모두 참</strong>일 때만 ‘원본 보관 완료’ 알림을 띄우세요. 응답의 <code>returnURL</code>을 <strong>URL 열기</strong>로 엽니다.</p><p>오류·미확인이라면 [원본 파일]과 [녹음 폴더]를 그대로 둡니다. 연결이 회복된 뒤 SPT의 <strong>같은 녹음</strong>에서 전송 연결을 새로 준비해 다시 실행하면, 폴더의 기존 파일을 사용합니다. ‘새 녹음 연결 준비’는 정말 새로운 녹음에만 사용하세요. 처리 결과가 미확인이면 SPT의 ‘처리 상태 확인’에서 대조합니다.</p></section>
 <section className="panel"><h2>첫 확인은 짧은 새 테스트</h2><p>SPT의 <strong>기록 목적: 기능 테스트</strong>로 새 대화를 준비하고 ‘자동 전송 연결 준비 → 녹음·자동 전송 시작’을 누르세요. 기존 9월 14일 녹음·전사 4개는 재사용하지 않습니다.</p><p>처음 한 번 폴더·마이크·네트워크 권한을 물을 수 있습니다. 이후 정상 흐름에서 저장 위치 선택이나 SPT 파일 재선택이 다시 나오는지 확인합니다. 실제 기기 동작명·파일 반환·통신 형식이 이 안내와 다르면 임의로 우회하지 말고 해당 단계만 알려주세요.</p><p><Link href="/">SPT로 돌아가기</Link></p></section>
 <footer><p>공식 동작 설명: <a href="https://support.apple.com/guide/shortcuts/run-a-shortcut-from-a-url-apd624386f42/ios" target="_blank" rel="noreferrer">단축어 입력 전달</a> · <a href="https://support.apple.com/guide/shortcuts/request-your-first-api-apd58d46713f/ios" target="_blank" rel="noreferrer">파일 본문 API 요청</a></p></footer>
 </main>;}
