#!/usr/bin/env bun
import { lstatSync, readFileSync, realpathSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';

export const managedRepositoryPath = '/workspace/dc-gang-a';
export const managedWorkspaceEntryPath = '/workspace/AGENTS.md';
const sourceRoot = resolve(import.meta.dir, '..');

/** Exact bytes, rather than a marker alone, establish ownership of this generated bridge. */
export const workspaceEntryContent = `# dc-gang-a managed workspace entry

Generated by dc-gang-a/harness/workspace_entry.ts. Applies only to this managed /workspace checkout.

- The project is /workspace/dc-gang-a. Read /workspace/dc-gang-a/AGENTS.md before project work, then use that directory as the working directory.
- Run bun run workflow:context at task start, after compaction, and before dispatching subagents. docs/workflow-routing.json owns contextReadRouting; select interview, dependencies, main_sheet, google_integration, academy_local, or spt_mobile as needed. Read the referenced context; the command returns routing metadata, not the documents' contents.
- Before product-purpose interviews, run bun run workflow:context interview and read docs/CODEX_CONTEXT.md, docs/WHOLE_LENS_DECISION.md, handoffs/workflow-current-state.json, and docs/workflow-routing.json from the project plus the returned required scope documents. These include docs/learning/domain-design.json, docs/learning/weekly-audit.json, docs/main-sheet-design.json, docs/main-sheet-live-refresh-wiring.json, and docs/google-api-enablement-proposal-2026-10-01.json. Ask only for unresolved choices after reconciling their dated provenance.
- Existing project purposes and user answers belong to those sources. Keep durable intent, dated evidence, current implementation, and unresolved requirements distinct; a later file date alone does not settle conflicts.
- Bun 1.4.2 is required. If bun is absent from PATH, use /workspace/.cloud-tools/bun-1.4.2/node_modules/@oven/bun-linux-x64/bin/bun and prepend that directory to PATH for the command so package scripts can also find bun. Use BUN_INSTALL_CACHE_DIR=/workspace/.cloud-tools/bun-cache when needed.
- This bridge installs no hooks and does not establish that the current session loaded native instructions. Preserve any existing user-authored parent guidance; do not overwrite it.
`;

export type WorkspaceEntryAction = 'apply' | 'check';
export type WorkspaceEntryStatus = 'created' | 'current' | 'missing' | 'conflict' | 'not_applicable';
type EntryKind = 'file' | 'directory' | 'symlink' | 'other' | 'missing';
export interface WorkspaceEntryIO {
  canonicalPath(path: string): string | null;
  kind(path: string): EntryKind;
  readText(path: string): string;
  createExclusive(path: string, content: string): void;
}
export interface WorkspaceEntryResult {
  ok: boolean;
  action: WorkspaceEntryAction;
  status: WorkspaceEntryStatus;
  applicable: boolean;
  changed: boolean;
  targetPath: typeof managedWorkspaceEntryPath | null;
  reason: string | null;
  effectivePromptLoaded: 'unverified';
  hooksInstalled: false;
  automaticPerTurnInjectionInstalled: false;
}

function missing(error: unknown): boolean {
  return (error as NodeJS.ErrnoException).code === 'ENOENT';
}
const diskIO: WorkspaceEntryIO = {
  canonicalPath(path) {
    try { return realpathSync(path); }
    catch (error) { if (missing(error)) return null; throw error; }
  },
  kind(path) {
    try {
      const stat = lstatSync(path);
      if (stat.isSymbolicLink()) return 'symlink';
      if (stat.isFile()) return 'file';
      if (stat.isDirectory()) return 'directory';
      return 'other';
    } catch (error) { if (missing(error)) return 'missing'; throw error; }
  },
  readText: path => readFileSync(path, 'utf8'),
  createExclusive: (path, content) => writeFileSync(path, content, { encoding: 'utf8', flag: 'wx', mode: 0o644 }),
};

function result(action: WorkspaceEntryAction, status: WorkspaceEntryStatus,
  reason: string | null = null): WorkspaceEntryResult {
  return {
    ok: status === 'created' || status === 'current' || status === 'not_applicable',
    action, status, applicable: status !== 'not_applicable', changed: status === 'created',
    targetPath: status === 'not_applicable' ? null : managedWorkspaceEntryPath, reason,
    effectivePromptLoaded: 'unverified', hooksInstalled: false, automaticPerTurnInjectionInstalled: false,
  };
}

function inspectManagedEntry(action: WorkspaceEntryAction, base: string, io: WorkspaceEntryIO): WorkspaceEntryResult {
  // Never inspect or create a parent entry for portable/CI checkouts on other hosts.
  if (resolve(base) !== managedRepositoryPath) return result(action, 'not_applicable', 'outside_fixed_managed_checkout');
  try {
    // A lexical /workspace path must not become a route into an unrelated host directory.
    if (io.canonicalPath('/workspace') !== '/workspace'
      || io.canonicalPath(managedRepositoryPath) !== managedRepositoryPath
      || io.kind('/workspace') !== 'directory' || io.kind(managedRepositoryPath) !== 'directory') {
      return result(action, 'not_applicable', 'managed_checkout_not_canonical_directory');
    }
    const kind = io.kind(managedWorkspaceEntryPath);
    if (kind === 'missing') return result(action, 'missing', 'native_parent_entry_missing');
    if (kind !== 'file') return result(action, 'conflict', 'parent_entry_not_regular_file');
    // Symlinks are rejected above without reading their target or printing any guidance.
    if (io.readText(managedWorkspaceEntryPath) !== workspaceEntryContent) {
      return result(action, 'conflict', 'existing_parent_guidance_preserved');
    }
    return result(action, 'current');
  } catch {
    return result(action, 'conflict', 'managed_entry_inspection_failed');
  }
}

/** Read-only artifact verification; it never asserts the managed session's effective prompt. */
export function checkWorkspaceEntry(base = sourceRoot, io: WorkspaceEntryIO = diskIO): WorkspaceEntryResult {
  return inspectManagedEntry('check', base, io);
}

/** Create the fixed managed bridge only when absent; existing guidance is never overwritten. */
export function applyWorkspaceEntry(base = sourceRoot, io: WorkspaceEntryIO = diskIO): WorkspaceEntryResult {
  const before = inspectManagedEntry('apply', base, io);
  if (before.status !== 'missing') return before;
  try {
    io.createExclusive(managedWorkspaceEntryPath, workspaceEntryContent);
  } catch (error) {
    // An entry created during the check/create interval is inspected, never replaced.
    if ((error as NodeJS.ErrnoException).code === 'EEXIST') return inspectManagedEntry('apply', base, io);
    return result('apply', 'conflict', 'managed_entry_creation_failed');
  }
  const after = inspectManagedEntry('apply', base, io);
  if (after.status !== 'current') return result('apply', 'conflict', 'managed_entry_readback_failed');
  return result('apply', 'created');
}

if (import.meta.main) {
  const action = process.argv[2];
  if (process.argv.length !== 3 || (action !== 'apply' && action !== 'check')) {
    console.error(JSON.stringify({ ok: false, reason: 'use_apply_or_check' }));
    process.exitCode = 1;
  } else {
    const entry = action === 'apply' ? applyWorkspaceEntry() : checkWorkspaceEntry();
    console.log(JSON.stringify(entry, null, 2));
    if (!entry.ok) process.exitCode = 1;
  }
}
