import {readRoster} from '@/lib/roster-server';
import {env} from 'cloudflare:workers';
import {clientRecordedAt} from '@/lib/provenance';
import {owner,db,body,result,failure,ApiError,ownedSession,connectionStatus} from '@/lib/server';
import {validateCard,isCardKind,canRestoreCard,type ObservationCard} from '@/lib/observation-cards';
import {validDate,uuid,text} from '@/lib/notebook';
import {rehearsalId} from '@/lib/rehearsal';
export const dynamic='force-dynamic';
export async function GET(request:Request){try{const user=await owner();const date=new URL(request.url).searchParams.get('date');if(!validDate(date))throw new ApiError('수업일을 확인해 주세요.');const sessions=await db().prepare('SELECT id,student_id,class_date,title,created_at,purpose,ended_at FROM spt_sessions WHERE owner=? AND class_date=? ORDER BY created_at,id').bind(user,date).all();const events=await db().prepare('SELECT e.id,e.session_id,e.kind,e.body,e.capture_id,e.created_at,e.recorded_at_client,e.base_revision_id,e.schema_version FROM spt_entries e JOIN spt_sessions s ON e.session_id=s.id WHERE e.owner=? AND s.class_date=? ORDER BY e.created_at,e.rowid').bind(user,date).all();const captures=await db().prepare('SELECT c.id,c.session_id,c.state,c.created_at,c.ended_at,COALESCE(ROUND(i.duration*16000),SUM(a.size)/2,0) samples,COUNT(a.id) chunks,CASE WHEN i.id IS NULL THEN \'browser\' ELSE \'file_import\' END audio_source,i.filename original_name FROM spt_captures c JOIN spt_sessions s ON c.session_id=s.id LEFT JOIN spt_audio_chunks a ON a.capture_id=c.id LEFT JOIN spt_audio_imports i ON i.id=c.id AND i.owner=c.owner WHERE c.owner=? AND s.class_date=? GROUP BY c.id ORDER BY c.created_at').bind(user,date).all();const connection=await connectionStatus(user);return result({rehearsalId:rehearsalId()||undefined,sessions:sessions.results,events:events.results,captures:captures.results,connected:connection.connected,connectionSource:connection.source,captureMode:(env as unknown as Record<string,unknown>).SPT_CAPTURE_MODE==='voice_memos'?'voice_memos':'browser',ownerKey:user,...await readRoster(user)});}catch(e){return failure(e)}}
export async function POST(request:Request){try{const user=await owner(request);const p=await body(request);if(!uuid(p.id))throw new ApiError('기록 ID가 올바르지 않습니다.');
 if(p.action==='end'){await ownedSession(p.id,user);await db().prepare('UPDATE spt_sessions SET ended_at=COALESCE(ended_at,?) WHERE id=? AND owner=?').bind(new Date().toISOString(),p.id,user).run();return result({saved:true,id:p.id});}
 if(p.action==='create'){if(!validDate(p.date)||!(await readRoster(user)).roster.some(s=>s.id===p.studentId))throw new ApiError('학생과 수업일을 확인해 주세요.');const title=text(p.title,150).trim()||'수업 대화';const purpose=p.purpose==='test'?'test':'lesson';const createdAt=typeof p.createdAt==='string'&&!isNaN(Date.parse(p.createdAt))?new Date(p.createdAt).toISOString():new Date().toISOString();const existing=await db().prepare('SELECT * FROM spt_sessions WHERE id=?').bind(p.id).first();if(existing){if(existing.owner!==user||existing.student_id!==p.studentId||existing.class_date!==p.date||existing.title!==title||existing.purpose!==purpose)throw new ApiError('같은 기록 ID의 내용이 다릅니다.',409);return result({saved:true,id:p.id});}await db().prepare('INSERT INTO spt_sessions(id,owner,student_id,class_date,title,created_at,purpose) VALUES(?,?,?,?,?,?,?)').bind(p.id,user,p.studentId,p.date,title,createdAt,purpose).run();return result({saved:true,id:p.id});}
 if(p.action!=='entry'||!uuid(p.sessionId))throw new ApiError('기록 종류를 확인해 주세요.');const session=await ownedSession(p.sessionId,user);const kinds=['observation','transcript','transcript_edit','ai_draft','review','review_draft','transcript_draft','recording_notice'];const cardRequest=typeof p.kind==='string'&&isCardKind(p.kind);if(!cardRequest&&!kinds.includes(p.kind))throw new ApiError('허용되지 않은 기록입니다.');let data:Record<string,unknown>={};
 if(cardRequest){if(p.studentId!==session.student_id||p.date!==session.class_date)throw new ApiError('관찰 학생과 수업일이 대화와 다릅니다.',409);try{data=validateCard(p.kind,p.data);}catch(e){throw new ApiError(e instanceof Error?e.message:'관찰 카드 형식을 확인해 주세요.');}if(!p.captureId&&data.positionSeconds!==null)throw new ApiError('원음 위치에 연결된 녹음을 확인해 주세요.');}
 else if(p.kind==='observation')data={observed:text(p.data.observed),studentSaid:text(p.data.studentSaid),next:text(p.data.next)};
 else if(p.kind==='review'){if(p.data.teacherConfirmed!==true)throw new ApiError('교사 검토 확인이 필요합니다.');data={summary:text(p.data.summary),needs:text(p.data.needs),next:text(p.data.next),teacherConfirmed:true,reason:text(p.data.reason||'수업 후 교사 검토',1000)};}
 else if(p.kind==='transcript_edit')data={text:text(p.data.text,100000),reason:text(p.data.reason,1000)};
 else data={text:text(p.data.text,100000)};
 let inputAt:string|null;try{inputAt=clientRecordedAt(p.recordedAtClient);}catch(e){throw new ApiError(e instanceof Error?e.message:'기기 입력 시각을 확인해 주세요.');}const revisionBase=typeof p.baseId==='string'?p.baseId:null;const serialized=JSON.stringify(data);const existing=await db().prepare('SELECT * FROM spt_entries WHERE id=?').bind(p.id).first();if(existing){if(existing.owner!==user||existing.session_id!==p.sessionId||existing.kind!==p.kind||existing.body!==serialized||existing.capture_id!==(p.captureId||'')||existing.schema_version!==null&&(existing.recorded_at_client!==inputAt||existing.base_revision_id!==revisionBase))throw new ApiError('저장 요청 내용이 달라 재시도할 수 없습니다.',409);return result({saved:true,id:p.id});}
 const editable=cardRequest||['observation','transcript_edit','ai_draft','review','review_draft','transcript_draft'].includes(p.kind);const base=typeof p.baseId==='string'?p.baseId:'';const captureId=p.captureId||'';
 if(captureId){const c=await db().prepare('SELECT id FROM spt_captures WHERE id=? AND owner=? AND session_id=?').bind(captureId,user,p.sessionId).first();if(!c)throw new ApiError('녹음 대상을 확인해 주세요.');}
 if(cardRequest){const card=data as ObservationCard;const previous=await db().prepare('SELECT id,session_id,body,capture_id FROM spt_entries WHERE owner=? AND kind=? ORDER BY rowid DESC LIMIT 1').bind(user,p.kind).first<{id:string;session_id:string;body:string;capture_id:string}>();if(previous){const oldCard=JSON.parse(previous.body) as ObservationCard;if(oldCard.deleted&&!canRestoreCard(oldCard,card,previous.id,base))throw new ApiError('최신 삭제 기록을 확인한 뒤 복원해 주세요.',409);if(!oldCard.deleted&&oldCard.restoredFrom!==card.restoredFrom)throw new ApiError('복원 이력은 직접 바꿀 수 없습니다.',409);if(previous.session_id!==p.sessionId)throw new ApiError('원래 학생의 대화를 다른 대화로 옮길 수 없습니다.',409);if(JSON.stringify(oldCard.scene)!==JSON.stringify(card.scene)||oldCard.occurrenceOf!==card.occurrenceOf||oldCard.positionSeconds!==card.positionSeconds||previous.capture_id!==captureId)throw new ApiError('기록한 장면과 원음 위치를 바꿀 수 없습니다.',409);}else if(card.deleted||card.restoredFrom)throw new ApiError('원래 카드가 먼저 저장되어야 합니다.',409);}
 const args=[p.id,user,p.sessionId,p.kind,serialized,captureId,new Date().toISOString(),inputAt,revisionBase,1];const query=editable?'INSERT OR IGNORE INTO spt_entries(id,owner,session_id,kind,body,capture_id,created_at,recorded_at_client,base_revision_id,schema_version) SELECT ?,?,?,?,?,?,?,?,?,? WHERE COALESCE((SELECT id FROM spt_entries WHERE owner=? AND session_id=? AND kind=? ORDER BY rowid DESC LIMIT 1),\'\')=?':'INSERT OR IGNORE INTO spt_entries(id,owner,session_id,kind,body,capture_id,created_at,recorded_at_client,base_revision_id,schema_version) VALUES(?,?,?,?,?,?,?,?,?,?)';
 const guarded=cardRequest?query+" AND NOT EXISTS (SELECT 1 FROM spt_entries WHERE owner=? AND kind=? AND session_id<>?)":query;const done=await db().prepare(guarded).bind(...args,...(editable?[user,p.sessionId,p.kind,base]:[]),...(cardRequest?[user,p.kind,p.sessionId]:[])).run();if(done.meta.changes!==1){const saved=await db().prepare('SELECT * FROM spt_entries WHERE id=?').bind(p.id).first();if(saved&&saved.owner===user&&saved.session_id===p.sessionId&&saved.kind===p.kind&&saved.body===serialized&&saved.capture_id===captureId&&saved.recorded_at_client===inputAt&&saved.base_revision_id===revisionBase)return result({saved:true,id:p.id});throw new ApiError('다른 창에서 이 기록을 수정했습니다. 입력을 복사해 보관한 뒤 최신 기록을 불러와 주세요.',409);}return result({saved:true,id:p.id});
 }catch(e){return failure(e)}}
