import {sqliteTable,text,integer,real,index,uniqueIndex} from 'drizzle-orm/sqlite-core';
export const sessions=sqliteTable('spt_sessions',{id:text('id').primaryKey(),owner:text('owner').notNull(),studentId:text('student_id').notNull(),classDate:text('class_date').notNull(),title:text('title').notNull(),createdAt:text('created_at').notNull(),purpose:text('purpose').notNull().default('lesson'),endedAt:text('ended_at')},t=>[index('sessions_owner_day').on(t.owner,t.classDate)]);
export const entries=sqliteTable('spt_entries',{id:text('id').primaryKey(),owner:text('owner').notNull(),sessionId:text('session_id').notNull().references(()=>sessions.id),kind:text('kind').notNull(),body:text('body').notNull(),captureId:text('capture_id').notNull().default(''),createdAt:text('created_at').notNull(),recordedAtClient:text('recorded_at_client'),baseRevisionId:text('base_revision_id'),schemaVersion:integer('schema_version')},t=>[index('entries_session').on(t.owner,t.sessionId,t.createdAt)]);
export const captures=sqliteTable('spt_captures',{id:text('id').primaryKey(),owner:text('owner').notNull(),sessionId:text('session_id').notNull().references(()=>sessions.id),state:text('state').notNull(),createdAt:text('created_at').notNull(),endedAt:text('ended_at')},t=>[index('captures_session').on(t.owner,t.sessionId)]);
export const chunks=sqliteTable('spt_audio_chunks',{id:text('id').primaryKey(),owner:text('owner').notNull(),captureId:text('capture_id').notNull().references(()=>captures.id),seq:integer('seq').notNull(),size:integer('size').notNull(),hash:text('hash').notNull(),objectKey:text('object_key').notNull(),createdAt:text('created_at').notNull()},t=>[uniqueIndex('chunks_capture_seq').on(t.captureId,t.seq)]);
export const secrets=sqliteTable('spt_secrets',{owner:text('owner').primaryKey(),cipher:text('cipher').notNull(),updatedAt:text('updated_at').notNull()});
// Immutable revisions: a classroom activity can keep its original lesson while
// the teacher explicitly schedules its remaining work for another meeting.
export const classEvents=sqliteTable('spt_class_events',{id:text('id').primaryKey(),owner:text('owner').notNull(),entityId:text('entity_id').notNull(),studentId:text('student_id').notNull(),classDate:text('class_date').notNull(),kind:text('kind').notNull(),body:text('body').notNull(),createdAt:text('created_at').notNull(),recordedAtClient:text('recorded_at_client'),baseRevisionId:text('base_revision_id'),schemaVersion:integer('schema_version')},t=>[index('class_events_owner_entity').on(t.owner,t.entityId),index('class_events_owner_day').on(t.owner,t.classDate)]);
export const sheetSettings=sqliteTable('spt_sheet_settings',{owner:text('owner').primaryKey(),mappings:text('mappings').notNull(),confirmedAt:text('confirmed_at').notNull(),leaseUntil:integer('lease_until').notNull().default(0),lastSyncAt:text('last_sync_at'),lastError:text('last_error').notNull().default(''),rosterRevisionId:text('roster_revision_id').notNull().default('')});
export const sheetSnapshots=sqliteTable('spt_sheet_snapshots',{id:text('id').primaryKey(),owner:text('owner').notNull(),classDate:text('class_date').notNull(),contentHash:text('content_hash').notNull(),body:text('body').notNull(),observedAt:text('observed_at').notNull()},t=>[index('sheet_snapshot_owner_day').on(t.owner,t.classDate)]);
export const sheetReceipts=sqliteTable('spt_sheet_receipts',{id:text('id').primaryKey(),owner:text('owner').notNull(),studentId:text('student_id').notNull(),classDate:text('class_date').notNull(),entryId:text('entry_id').notNull(),remoteId:text('remote_id').notNull(),sourceSignature:text('source_signature').notNull(),remoteRevision:text('remote_revision').notNull(),createdAt:text('created_at').notNull()},t=>[uniqueIndex('sheet_receipt_owner_entry').on(t.owner,t.entryId),index('sheet_receipt_owner_student_day').on(t.owner,t.studentId,t.classDate)]);

export const rosterRevisions=sqliteTable('spt_roster_revisions',{id:text('id').primaryKey(),owner:text('owner').notNull(),body:text('body').notNull(),sourceHash:text('source_hash').notNull(),createdAt:text('created_at').notNull()},t=>[index('roster_revision_owner').on(t.owner)]);
export const audioImports=sqliteTable('spt_audio_imports',{id:text('id').primaryKey(),owner:text('owner').notNull(),sessionId:text('session_id').notNull().references(()=>sessions.id),filename:text('filename'),mime:text('mime'),size:integer('size'),status:text('status').notNull().default('prepared'),createdAt:text('created_at').notNull(),updatedAt:text('updated_at').notNull(),duration:real('duration'),attemptId:text('attempt_id'),transcriptId:text('transcript_id'),error:text('error')},t=>[index('imports_owner_session').on(t.owner,t.sessionId)]);
export const audioImportParts=sqliteTable('spt_audio_import_parts',{id:text('id').primaryKey(),owner:text('owner').notNull(),importId:text('import_id').notNull().references(()=>audioImports.id),seq:integer('seq').notNull(),size:integer('size').notNull(),hash:text('hash').notNull(),objectKey:text('object_key').notNull()},t=>[uniqueIndex('import_parts_sequence').on(t.importId,t.seq)]);
