import test from 'node:test';
import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {mkdirSync} from 'node:fs';
import {pathToFileURL} from 'node:url';
import {build} from 'esbuild';
const out='.sites-runtime/autonomous-ui/contracts';mkdirSync(out,{recursive:true});
await build({stdin:{contents:"export * from './lib/classroom-view';export {task} from './lib/classroom';export {closeoutEvidenceBasis} from './lib/closeout-review';",resolveDir:process.cwd()},outfile:out+'/view.mjs',bundle:true,format:'esm',platform:'node'});
const m=await import(pathToFileURL(process.cwd()+'/'+out+'/view.mjs'));
const date='2026-09-14';
function fixture(){return {ledger:[],sessions:[],events:[],captures:[],connected:false,localItems:[]};}
function activity(sid,title,state='working',lane='student'){return {id:randomUUID(),entity_id:randomUUID(),student_id:sid,class_date:date,kind:'activity',body:JSON.stringify({...m.task(title,date),state,lane}),created_at:'2026-09-14T06:00:00.000Z'};}
function close(data,sid='A'){const row={id:randomUUID(),entity_id:'closeout:'+sid+':'+date,student_id:sid,class_date:date,kind:'closeout',body:JSON.stringify({progress:'SYNTHETIC',homework:'',due:'',noHomework:true,next:'',confirmed:true,departedAt:'',evidenceBasis:m.closeoutEvidenceBasis(sid,date,data)})};data.ledger.push(row);return row;}
test('student work and teacher follow-up coexist; no inferred attendance or mastery',()=>{const d=fixture(),a=activity('A','Synthetic work'),b=activity('A','Teacher discussion','assigned','teacher');d.ledger.push(a,b,activity('B','Other work'));const v=m.classroomView('A',date,d,b.entity_id);assert.equal(v.current.event.id,a.id);assert.deepEqual(v.followups.map(x=>x.event.id),[b.id]);assert.equal(v.status.departedAt,'');assert.equal(v.confirmation,'missing');assert.equal('mastery' in v,false);});
test('a changed evidence revision invalidates confirmation, without erasing its source',()=>{const d=fixture(),e=close(d);assert.equal(m.classroomView('A',date,d).confirmation,'confirmed');d.ledger.push(activity('A','Later evidence'));const v=m.classroomView('A',date,d);assert.equal(v.confirmation,'stale');assert.equal(v.record.id,e.id);assert.equal(v.closeout.confirmed,true);assert.equal(v.reflection,'unconfirmed');});
test('exact pending/blocked/acknowledged revision is independent of teacher confirmation',()=>{const d=fixture(),e=close(d);e.local_projection=true;const job={key:'synthetic',owner:'synthetic',type:'job',order:1,url:'/api/classroom',payload:{id:e.id,entityId:e.entity_id,studentId:'A',date}};d.localItems=[job];let v=m.classroomView('A',date,d);assert.equal(v.confirmation,'confirmed');assert.equal(v.retention,'pending');assert.equal(v.reflection,'unknown');job.error='SYNTHETIC conflict';assert.equal(m.classroomView('A',date,d).retention,'blocked');job.type='receipt';delete job.error;assert.equal(m.classroomView('A',date,d).retention,'server');job.payload.studentId='B';assert.equal(m.classroomView('A',date,d).retention,'unknown');});
test('original reflection requires the same student, day, revision and observed latest row',()=>{const d=fixture(),e=close(d);const sheet={date,configured:true,connected:true,mappings:[{studentId:'A',active:true,trackerRevision:'r1'}],receipts:[{student_id:'A',class_date:date,entry_id:e.id,remote_id:'remote-a',remote_revision:'r1'}],baselines:[{student_id:'A',remote_revision:'r1'}],snapshot:{date,tracker:{students:[{studentId:'A',revision:'r1',latestReview:{id:'remote-a',data:{sourceId:e.id}}}]}}};d.sheet=sheet;assert.equal(m.classroomView('A',date,d).reflection,'reflected');sheet.snapshot.tracker.students[0].latestReview.id='new-remote';assert.equal(m.classroomView('A',date,d).reflection,'conflict');sheet.date='2026-09-15';assert.equal(m.classroomView('A',date,d).reflection,'unknown');sheet.date=date;sheet.receipts[0].student_id='B';assert.notEqual(m.classroomView('A',date,d).reflection,'reflected');});
test('ordinary evidence excludes other subjects/days and both explicit and historical tests',()=>{const d=fixture();d.sessions=[{id:randomUUID(),student_id:'A',class_date:date,purpose:'lesson'},{id:randomUUID(),student_id:'A',class_date:date,purpose:'test'},{id:'11111111-1111-4111-8111-111111111111',student_id:'A',class_date:date,purpose:'lesson'},{id:randomUUID(),student_id:'B',class_date:date,purpose:'lesson'},{id:randomUUID(),student_id:'A',class_date:'2026-09-15',purpose:'lesson'}];assert.equal(m.classroomView('A',date,d).sources.length,1);});
test('an unobserved day is unknown, not an observed empty or never-reviewed day',()=>{const d=fixture();d.classroomLoaded=false;const v=m.classroomView('A',date,d);assert.equal(v.confirmation,'unknown');assert.equal(v.retention,'unknown');assert.equal(v.activityRetention,'unknown');d.classroomLoaded=true;assert.equal(m.classroomView('A',date,d).confirmation,'missing');});
test('an instruction/departure-only student still has a retained classroom record',()=>{const d=fixture();d.ledger.push({id:randomUUID(),entity_id:'class_status:A:'+date,student_id:'A',class_date:date,kind:'class_status',body:JSON.stringify({instructionAt:'2026-09-14T07:00:00.000Z',departedAt:''})});const v=m.classroomView('A',date,d);assert.equal(v.activityRetention,'server');assert.equal(v.confirmation,'missing');});
test('mutable projected activity/session outputs do not alter the next result or evidence',()=>{const d=fixture(),e=activity('A','Synthetic work');d.ledger.push(e);d.sessions.push({id:randomUUID(),student_id:'A',class_date:date,purpose:'lesson'});const v=m.classroomView('A',date,d);v.current.event.student_id='B';v.current.task.title='changed';v.sources[0].student_id='B';const next=m.classroomView('A',date,d);assert.equal(next.current.event.student_id,'A');assert.equal(next.current.task.title,'Synthetic work');assert.equal(next.sources.length,1);});
