import {test} from 'node:test';import assert from 'node:assert/strict';import {build} from 'esbuild';import {writeFileSync} from 'node:fs';
const h={slots:[],at:0};globalThis.__hvHooks=h;
const runtime=`const h=globalThis.__hvHooks;export function useRef(v){const i=h.at++;return h.slots[i]??(h.slots[i]={current:v})}export function useState(v){const i=h.at++;if(!(i in h.slots))h.slots[i]=typeof v==='function'?v():v;return [h.slots[i],v=>h.slots[i]=typeof v==='function'?v(h.slots[i]):v]}export function useEffect(){}export function useLayoutEffect(fn){fn()}export function useId(){return useRef('hv'+h.at).current}`;
const b=await build({stdin:{contents:"export {ClassroomBoard,StudentCycleCard} from './app/classroom-board';export {TaskCard,ReviewPanel} from './app/classroom-panels';export {task} from './lib/classroom';export * from './lib/havruta';export {HavrutaPanel,HavrutaRound} from './app/havruta-panel';",resolveDir:process.cwd()},bundle:true,platform:'node',format:'esm',write:false,external:['react/jsx-runtime','lucide-react'],plugins:[{name:'hooks',setup(b){b.onResolve({filter:/^react$/},()=>({path:'react',namespace:'hooks'}));b.onLoad({filter:/.*/,namespace:'hooks'},()=>({contents:runtime}));b.onResolve({filter:/components\/ui\//},a=>({path:a.path,namespace:'ui'}));b.onLoad({filter:/.*/,namespace:'ui'},()=>({contents:['Checkbox','Select','SelectContent','SelectItem','SelectTrigger','SelectValue','Dialog','DialogContent','DialogHeader','DialogTitle','DialogDescription'].map(n=>`export const ${n}='${n}';`).join('\n')}));}}]});writeFileSync('.sites-runtime/havruta-27b335/ui-test.mjs',b.outputFiles[0].text);const ui=await import('../.sites-runtime/havruta-27b335/ui-test.mjs');
const render=(fn,p)=>{h.at=0;return fn(p)},find=(n,f)=>{if(!n||typeof n!=='object')return null;if(f(n))return n;for(const c of [n.props?.children].flat(Infinity)){const r=find(c,f);if(r)return r;}return null;};
const students=['A','B','C'].map(id=>({id:'QA_'+id,name:'Synthetic '+id,days:[1],part:'1부',time:'15:00–17:30',firstDate:'2039-01-01',books:[]})),date='2040-01-02';
test('whole-class board exposes a real collaborative consumer rather than a scalar title only',()=>{h.slots=[];const tree=render(ui.ClassroomBoard,{students,date,ledger:[],data:{ledger:[],sessions:[],events:[],captures:[],connected:false},ready:true,view:'class',save:async()=>{},onOpen(){},onAudio(){},fail(e){throw e;}});assert.ok(find(tree,n=>n.type?.name==='HavrutaPanel'),'shared Havruta consumer missing');});
const all=(n,f)=>{if(!n||typeof n!=='object')return [];return [...(f(n)?[n]:[]),...[n.props?.children].flat(Infinity).flatMap(c=>all(c,f))];},tick=()=>new Promise(setImmediate);
function fixture(){const members=students.map(s=>({studentId:s.id,activityId:crypto.randomUUID()})),hv={version:1,groupId:crypto.randomUUID(),date,members,problem:{kind:'teacher_issued'},review:null};return members.map(m=>({id:crypto.randomUUID(),entity_id:m.activityId,student_id:m.studentId,class_date:date,kind:'activity',body:JSON.stringify({...ui.task('하브루타',date),state:'student_done',havruta:hv})}));}
test('round passes only explicitly selected reviewed subjects and rejects stale selection',async()=>{
 h.slots=[];const ledger=fixture(),writes=[],props={group:ui.havrutaGroups(ledger,date)[0],date,data:{ledger,localItems:[]},names:students,ready:true,save:async(...args)=>writes.push(args),onOpen(){},fail(e){throw e;}};
 let tree=render(ui.HavrutaRound,props),inputs=all(tree,n=>n.type==='input');inputs[0].props.onChange();inputs[2].props.onChange();tree=render(ui.HavrutaRound,props);find(tree,n=>n.type==='button'&&n.props.children==='설명 확인·선택 학생 통과').props.onClick();await tick();assert.deepEqual(writes.map(w=>w[0]),['QA_A','QA_C']);assert.ok(writes.every(w=>w[3].havruta.review.decision==='pass'));assert.equal(JSON.parse(ledger[1].body).state,'student_done');
 tree=render(ui.HavrutaRound,props);all(tree,n=>n.type==='input')[1].props.onChange();props.group=ui.havrutaGroups(ledger.map((e,i)=>i===1?{...e,id:crypto.randomUUID()}:e),date)[0];tree=render(ui.HavrutaRound,props);find(tree,n=>n.type==='button'&&n.props.children==='설명 확인·선택 학생 통과').props.onClick();await tick();assert.equal(writes.length,2);
});
test('partial local creation keeps stable member IDs and retries only the unretained student',async()=>{
 h.slots=[];let value=null,rev='',failB=true;const writes=[],data={ledger:[],localItems:[]},box={noteDraft:()=>value,storedNoteDraft:()=>value,recoveredNotes:()=>[],rememberNoteDraft(){},async saveNoteDraft(k,v,b){assert.equal(b,rev);rev=crypto.randomUUID();value={...v,revision:rev};return rev;}};
 const props={students,date,data,box,ready:true,onOpen(){},fail(){},save:async(sid,kind,id,body,day,base,mode,requestId)=>{writes.push({sid,id,body,requestId});if(sid==='QA_B'&&failB){failB=false;throw new Error('Synthetic local retention failure');}data.ledger.push({id:requestId,entity_id:id,student_id:sid,class_date:day,kind,body:JSON.stringify(body)});return {id:requestId};}};
 let tree=render(ui.HavrutaPanel,props);for(const i of all(tree,n=>n.type==='input'))i.props.onChange();await tick();tree=render(ui.HavrutaPanel,props);find(tree,n=>n.type==='button'&&n.props.children==='선택 학생에게 협동문제 배정').props.onClick();await tick();assert.equal(data.ledger.length,2);const ids=value.members.map(x=>x.activityId),groupId=value.groupId;tree=render(ui.HavrutaPanel,props);find(tree,n=>n.type==='button'&&n.props.children==='남은 대상 이어 배정').props.onClick();await tick();assert.equal(data.ledger.length,3);assert.equal(writes.length,4);assert.equal(writes[1].id,writes[3].id);assert.ok(writes.every(w=>w.requestId===w.id&&w.body.havruta.groupId===groupId));assert.deepEqual(data.ledger.map(e=>e.entity_id).sort(),ids.sort());
});
test('after-class evidence labels consume current Havruta validity, not raw done',()=>{
 h.slots=[];const ledger=fixture(),t=JSON.parse(ledger[0].body);const passed={...t,...ui.havrutaStatePatch(t,'done')};ledger[0]={...ledger[0],body:JSON.stringify({...passed,range:'changed after pass'})};
 const tree=render(ui.ReviewPanel,{studentId:'QA_A',date,data:{ledger,roster:students,sessions:[],events:[],captures:[],connected:false},save:async()=>{},fail(){},copy(){},onSource(){}});
 const text=n=>n==null||typeof n==='boolean'?'':typeof n==='string'||typeof n==='number'?String(n):[n.props?.children].flat(Infinity).map(text).join(' ');
 const evidence=find(tree,n=>n.props?.['aria-label']==='수업 검토 근거');assert.match(text(evidence),/재확인/);assert.doesNotMatch(text(evidence),/활동 확인 마침/);
});


